package com.jpatch.boundary;

import com.jpatch.settings.*;
import com.jpatch.afw.attributes.CollectionAttr;
import com.jpatch.afw.vecmath.Transform;
import com.jpatch.afw.vecmath.TransformUtil;
import com.jpatch.afw.vecmath.Utils3d;
import static com.jpatch.afw.vecmath.TransformUtil.*;
import com.jpatch.boundary.tools.*;
import com.jpatch.entity.*;
import com.jpatch.entity.sds2.*;
import com.sun.opengl.util.*;
//import com.sun.opengl.util.*;

import java.awt.Component;
import java.awt.event.MouseWheelEvent;
import java.awt.event.MouseWheelListener;
import java.io.*;
import java.nio.*;
import java.util.*;

import javax.media.opengl.*;

import static javax.media.opengl.GL.*;

import javax.vecmath.*;



public class ViewportGl extends Viewport {
	private static Matrix4d IDENTITY = Utils3d.createIdentityMatrix4d();
	private int repaintCount = 0;
	
	private static final boolean LIGHTWEIGHT = false;
//	private static final double CLEAR_DEPTH = 100000;
	private static final ColorSettings COLORS = Settings.getInstance().colors;
	private static final RealtimeRendererSettings RENDERER = Settings.getInstance().realtimeRenderer;
	
	private static final BasicMaterial BACK_MATERIAL = new BasicMaterial(new Color4f(), new Color4f(), new Color4f(), new Color4f(1, 0, 0, 1), 0);
	private static final BasicMaterial LINE_MATERIAL = new BasicMaterial(new Color4f(0.5f, 0.5f, 0.5f, 1.0f), new Color4f(0.5f, 0.5f, 0.5f, 1.0f), new Color4f(1, 1, 1, 1), new Color4f(), 100);
	private static final Color4f LINE_COLOR = new Color4f(1, 1, 1, 1);
	
	final GLAutoDrawable drawable;
//	private GL gl;
	private final Point3f p = new Point3f();
	private final Vector3f v = new Vector3f();
	
//	private final FragmentTesselator kernel = new FragmentTesselator();
//	private static final Dicer dicer = new Dicer();
	private int subdivLevel = 4;
	
	private long time;
	
	private int program;
	private boolean useProgram;
	private boolean canUseProgram;
	private int num;
	
	
	
	private double[] modelView = new double[16];
	
//	private Matrix4f modelView = new Matrix4f();
	private TransformUtil transformUtil = new TransformUtil();
//	private final TransformUtil transformUtil = new TransformUtil();
	
	private boolean screenshotTextureValid;
	private boolean depthBufferValid;
	private long lastRedrawTime;
	private int screenshotTexture;
	private float[] screenShotTxCoords = new float[4];
	private FloatBuffer depthBuffer;
	
	/**
	 * The unicode characters 0 to 255 as 16x14 bitmaps (autogenerated from
	 * default "Sans Serif" 14 font).
	 */
	private static final byte[][] fontRaster = new byte[][] {
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,64,0,0,0,64,0,64,0,64,0,64,0,64,0,64,0,64,0,0,0,0,0,0,0},
		{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-96,0,-96,0,-96,0,0,0,0,0,0,0},
		{0,0,0,0,72,0,72,0,36,0,-2,0,36,0,127,0,36,0,18,0,18,0,0,0,0,0,0,0},
		{0,0,16,0,56,0,84,0,20,0,20,0,56,0,80,0,80,0,84,0,56,0,16,0,0,0,0,0},
		{0,0,0,0,-122,0,73,0,41,0,22,0,16,0,104,0,-108,0,-110,0,97,0,0,0,0,0,0,0},
		{0,0,0,0,62,0,68,0,74,0,74,0,50,0,40,0,36,0,36,0,24,0,0,0,0,0,0,0},
		{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,64,0,64,0,64,0,0,0,0,0,0,0},
		{16,0,32,0,32,0,64,0,64,0,64,0,64,0,64,0,32,0,32,0,16,0,0,0,0,0,0,0},
		{-128,0,64,0,64,0,32,0,32,0,32,0,32,0,32,0,64,0,64,0,-128,0,0,0,0,0,0,0},
		{0,0,0,0,0,0,0,0,0,0,0,0,0,0,80,0,80,0,-8,0,32,0,0,0,0,0,0,0},
		{0,0,0,0,8,0,8,0,8,0,127,0,8,0,8,0,8,0,0,0,0,0,0,0,0,0,0,0},
		{-128,0,64,0,64,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,0,0,0,0,0,0,124,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,64,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
		{64,0,64,0,32,0,32,0,32,0,16,0,16,0,16,0,16,0,8,0,8,0,0,0,0,0,0,0},
		{0,0,0,0,24,0,36,0,66,0,66,0,66,0,66,0,66,0,36,0,24,0,0,0,0,0,0,0},
		{0,0,0,0,62,0,8,0,8,0,8,0,8,0,8,0,8,0,40,0,24,0,0,0,0,0,0,0},
		{0,0,0,0,124,0,64,0,32,0,16,0,8,0,4,0,4,0,4,0,120,0,0,0,0,0,0,0},
		{0,0,64,0,56,0,4,0,4,0,8,0,48,0,8,0,4,0,4,0,120,0,0,0,0,0,0,0},
		{0,0,0,0,4,0,4,0,4,0,126,0,68,0,36,0,20,0,12,0,4,0,0,0,0,0,0,0},
		{0,0,0,0,112,0,8,0,4,0,4,0,8,0,112,0,64,0,64,0,124,0,0,0,0,0,0,0},
		{0,0,0,0,24,0,36,0,66,0,66,0,100,0,88,0,64,0,32,0,30,0,0,0,0,0,0,0},
		{0,0,0,0,32,0,32,0,16,0,16,0,8,0,8,0,4,0,2,0,126,0,0,0,0,0,0,0},
		{0,0,0,0,60,0,66,0,66,0,66,0,60,0,36,0,66,0,66,0,60,0,0,0,0,0,0,0},
		{0,0,0,0,120,0,4,0,2,0,26,0,38,0,66,0,66,0,36,0,24,0,0,0,0,0,0,0},
		{0,0,0,0,64,0,0,0,0,0,0,0,0,0,0,0,64,0,0,0,0,0,0,0,0,0,0,0},
		{-128,0,64,0,64,0,0,0,0,0,0,0,0,0,0,0,64,0,0,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,1,0,6,0,8,0,48,0,8,0,6,0,1,0,0,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,0,0,0,0,63,0,0,0,63,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,32,0,24,0,4,0,3,0,4,0,24,0,32,0,0,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,64,0,0,0,64,0,64,0,32,0,16,0,8,0,8,0,-16,0,0,0,0,0,0,0},
		{0,0,0,0,30,0,32,0,75,0,86,-128,82,64,73,64,39,64,16,-128,15,0,0,0,0,0,0,0},
		{0,0,0,0,-128,-128,65,0,127,0,34,0,34,0,20,0,20,0,8,0,8,0,0,0,0,0,0,0},
		{0,0,0,0,120,0,68,0,68,0,68,0,120,0,68,0,68,0,68,0,120,0,0,0,0,0,0,0},
		{0,0,0,0,30,0,32,0,64,0,64,0,64,0,64,0,64,0,32,0,30,0,0,0,0,0,0,0},
		{0,0,0,0,124,0,66,0,65,0,65,0,65,0,65,0,65,0,66,0,124,0,0,0,0,0,0,0},
		{0,0,0,0,126,0,64,0,64,0,64,0,124,0,64,0,64,0,64,0,126,0,0,0,0,0,0,0},
		{0,0,0,0,64,0,64,0,64,0,64,0,120,0,64,0,64,0,64,0,120,0,0,0,0,0,0,0},
		{0,0,0,0,31,0,33,0,65,0,65,0,64,0,64,0,64,0,32,0,31,0,0,0,0,0,0,0},
		{0,0,0,0,65,0,65,0,65,0,65,0,127,0,65,0,65,0,65,0,65,0,0,0,0,0,0,0},
		{0,0,0,0,64,0,64,0,64,0,64,0,64,0,64,0,64,0,64,0,64,0,0,0,0,0,0,0},
		{-64,0,32,0,32,0,32,0,32,0,32,0,32,0,32,0,32,0,32,0,32,0,0,0,0,0,0,0},
		{0,0,0,0,65,0,66,0,68,0,72,0,80,0,112,0,72,0,68,0,66,0,0,0,0,0,0,0},
		{0,0,0,0,124,0,64,0,64,0,64,0,64,0,64,0,64,0,64,0,64,0,0,0,0,0,0,0},
		{0,0,0,0,65,0,73,0,73,0,85,0,85,0,85,0,99,0,99,0,65,0,0,0,0,0,0,0},
		{0,0,0,0,65,0,67,0,69,0,69,0,73,0,81,0,81,0,97,0,65,0,0,0,0,0,0,0},
		{0,0,0,0,28,0,34,0,65,0,65,0,65,0,65,0,65,0,34,0,28,0,0,0,0,0,0,0},
		{0,0,0,0,64,0,64,0,64,0,64,0,120,0,68,0,68,0,68,0,120,0,0,0,0,0,0,0},
		{1,-128,2,0,28,0,34,0,65,0,65,0,65,0,65,0,65,0,34,0,28,0,0,0,0,0,0,0},
		{0,0,0,0,65,0,66,0,68,0,72,0,120,0,68,0,66,0,66,0,124,0,0,0,0,0,0,0},
		{0,0,0,0,-16,0,8,0,8,0,8,0,48,0,64,0,-128,0,-128,0,124,0,0,0,0,0,0,0},
		{0,0,0,0,16,0,16,0,16,0,16,0,16,0,16,0,16,0,16,0,-2,0,0,0,0,0,0,0},
		{0,0,0,0,60,0,66,0,66,0,66,0,66,0,66,0,66,0,66,0,66,0,0,0,0,0,0,0},
		{0,0,0,0,16,0,16,0,40,0,40,0,40,0,68,0,68,0,-126,0,-126,0,0,0,0,0,0,0},
		{0,0,0,0,17,0,17,0,42,-128,42,-128,42,-128,42,-128,42,-128,68,64,68,64,0,0,0,0,0,0},
		{0,0,0,0,-126,0,68,0,40,0,40,0,16,0,40,0,40,0,68,0,-126,0,0,0,0,0,0,0},
		{0,0,0,0,16,0,16,0,16,0,16,0,16,0,40,0,40,0,68,0,-126,0,0,0,0,0,0,0},
		{0,0,0,0,124,0,64,0,32,0,32,0,16,0,8,0,8,0,4,0,124,0,0,0,0,0,0,0},
		{96,0,64,0,64,0,64,0,64,0,64,0,64,0,64,0,64,0,64,0,96,0,0,0,0,0,0,0},
		{8,0,8,0,16,0,16,0,16,0,32,0,32,0,32,0,32,0,64,0,64,0,0,0,0,0,0,0},
		{96,0,32,0,32,0,32,0,32,0,32,0,32,0,32,0,32,0,32,0,96,0,0,0,0,0,0,0},
		{0,0,0,0,0,0,0,0,0,0,-126,0,68,0,68,0,40,0,16,0,16,0,0,0,0,0,0,0},
		{0,0,120,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,8,0,16,0,0,0,0,0},
		{0,0,0,0,62,0,68,0,68,0,60,0,4,0,68,0,56,0,0,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,92,0,98,0,66,0,66,0,66,0,98,0,92,0,64,0,64,0,0,0,0,0,0,0},
		{0,0,0,0,56,0,64,0,64,0,64,0,64,0,64,0,56,0,0,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,58,0,70,0,66,0,66,0,66,0,70,0,58,0,2,0,2,0,0,0,0,0,0,0},
		{0,0,0,0,60,0,64,0,64,0,124,0,68,0,68,0,56,0,0,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,64,0,64,0,64,0,64,0,64,0,64,0,-32,0,64,0,48,0,0,0,0,0,0,0},
		{120,0,4,0,52,0,76,0,68,0,68,0,68,0,68,0,60,0,0,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,68,0,68,0,68,0,68,0,68,0,100,0,88,0,64,0,64,0,0,0,0,0,0,0},
		{0,0,0,0,64,0,64,0,64,0,64,0,64,0,64,0,64,0,0,0,64,0,0,0,0,0,0,0},
		{-64,0,32,0,32,0,32,0,32,0,32,0,32,0,32,0,32,0,0,0,32,0,0,0,0,0,0,0},
		{0,0,0,0,66,0,68,0,72,0,112,0,80,0,72,0,68,0,64,0,64,0,0,0,0,0,0,0},
		{0,0,0,0,64,0,64,0,64,0,64,0,64,0,64,0,64,0,64,0,64,0,0,0,0,0,0,0},
		{0,0,0,0,68,64,68,64,68,64,68,64,68,64,102,64,89,-128,0,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,68,0,68,0,68,0,68,0,68,0,100,0,88,0,0,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,56,0,68,0,68,0,68,0,68,0,68,0,56,0,0,0,0,0,0,0,0,0,0,0},
		{64,0,64,0,92,0,98,0,66,0,66,0,66,0,98,0,92,0,0,0,0,0,0,0,0,0,0,0},
		{2,0,2,0,58,0,70,0,66,0,66,0,66,0,70,0,58,0,0,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,64,0,64,0,64,0,64,0,64,0,96,0,88,0,0,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,112,0,8,0,8,0,48,0,64,0,64,0,56,0,0,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,32,0,64,0,64,0,64,0,64,0,64,0,-32,0,64,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,52,0,76,0,68,0,68,0,68,0,68,0,68,0,0,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,16,0,40,0,40,0,40,0,68,0,68,0,-126,0,0,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,34,0,34,0,85,0,85,0,85,0,-120,-128,-120,-128,0,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,68,0,40,0,40,0,16,0,40,0,40,0,68,0,0,0,0,0,0,0,0,0,0,0},
		{32,0,16,0,16,0,40,0,40,0,68,0,68,0,-126,0,-126,0,0,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,124,0,64,0,32,0,16,0,8,0,4,0,124,0,0,0,0,0,0,0,0,0,0,0},
		{32,0,64,0,64,0,64,0,64,0,-128,0,64,0,64,0,64,0,64,0,32,0,0,0,0,0,0,0},
		{64,0,64,0,64,0,64,0,64,0,64,0,64,0,64,0,64,0,64,0,64,0,0,0,0,0,0,0},
		{64,0,32,0,32,0,32,0,32,0,16,0,32,0,32,0,32,0,32,0,64,0,0,0,0,0,0,0},
		{0,0,0,0,0,0,0,0,0,0,76,0,50,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
		{64,0,64,0,64,0,64,0,64,0,64,0,64,0,0,0,64,0,0,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,16,0,60,0,112,0,80,0,80,0,80,0,80,0,60,0,16,0,0,0,0,0,0,0},
		{0,0,0,0,126,0,32,0,32,0,32,0,120,0,32,0,32,0,32,0,30,0,0,0,0,0,0,0},
		{0,0,0,0,0,0,-126,0,124,0,68,0,68,0,68,0,124,0,-126,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,16,0,16,0,124,0,16,0,124,0,16,0,40,0,68,0,-126,0,0,0,0,0,0,0},
		{64,0,64,0,64,0,64,0,0,0,0,0,0,0,64,0,64,0,64,0,64,0,0,0,0,0,0,0},
		{124,0,2,0,2,0,28,0,34,0,66,0,68,0,56,0,64,0,64,0,62,0,0,0,0,0,0,0},
		{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,40,0,0,0,0,0,0,0},
		{0,0,0,0,62,0,65,0,-100,-128,-96,-128,-96,-128,-96,-128,-100,-128,65,0,62,0,0,0,0,0,0,0},
		{0,0,0,0,0,0,0,0,0,0,0,0,0,0,120,0,112,0,16,0,96,0,0,0,0,0,0,0},
		{0,0,0,0,0,0,20,0,40,0,80,0,40,0,20,0,0,0,0,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,0,0,0,0,1,0,1,0,63,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,0,0,0,0,0,0,124,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,0,0,0,0,0,0,0,0,56,0,84,0,84,0,68,0,56,0,0,0,0,0,0,0},
		{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-8,0,0,0,0,0},
		{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,112,0,80,0,112,0,0,0,0,0,0,0},
		{0,0,0,0,62,0,0,0,8,0,8,0,62,0,8,0,8,0,0,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,0,0,0,0,0,0,112,0,64,0,32,0,16,0,16,0,96,0,0,0,0,0,0,0},
		{0,0,0,0,0,0,0,0,0,0,96,0,16,0,16,0,96,0,16,0,96,0,0,0,0,0,0,0},
		{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,32,0,16,0,0,0,0,0},
		{64,0,64,0,116,0,76,0,68,0,68,0,68,0,68,0,68,0,0,0,0,0,0,0,0,0,0,0},
		{10,0,10,0,10,0,10,0,10,0,10,0,10,0,26,0,58,0,58,0,30,0,0,0,0,0,0,0},
		{0,0,0,0,0,0,0,0,0,0,64,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
		{8,0,16,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,0,0,0,0,0,0,112,0,32,0,32,0,32,0,96,0,32,0,0,0,0,0,0,0},
		{0,0,0,0,0,0,0,0,0,0,0,0,0,0,48,0,72,0,72,0,48,0,0,0,0,0,0,0},
		{0,0,0,0,0,0,-96,0,80,0,40,0,80,0,-96,0,0,0,0,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,64,-128,35,-64,18,-128,49,-128,41,-128,36,-128,36,0,98,0,33,0,0,0,0,0,0,0},
		{0,0,0,0,67,-128,34,0,17,0,48,-128,40,-128,39,0,36,0,98,0,33,0,0,0,0,0,0,0},
		{0,0,0,0,32,-128,19,-64,10,-128,105,-128,21,-128,18,-128,98,0,17,0,96,-128,0,0,0,0,0,0},
		{120,0,-128,0,-128,0,64,0,32,0,16,0,16,0,0,0,16,0,0,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,-128,-128,65,0,127,0,34,0,34,0,20,0,20,0,8,0,8,0,0,0,4,0,8,0},
		{0,0,0,0,-128,-128,65,0,127,0,34,0,34,0,20,0,20,0,8,0,8,0,0,0,8,0,4,0},
		{0,0,0,0,-128,-128,65,0,127,0,34,0,34,0,20,0,20,0,8,0,8,0,0,0,20,0,8,0},
		{0,0,0,0,-128,-128,65,0,127,0,34,0,34,0,20,0,20,0,8,0,8,0,0,0,44,0,52,0},
		{0,0,0,0,-128,-128,65,0,127,0,34,0,34,0,20,0,20,0,8,0,8,0,0,0,20,0,0,0},
		{0,0,0,0,-128,-128,65,0,127,0,34,0,34,0,20,0,20,0,8,0,8,0,28,0,20,0,28,0},
		{0,0,0,0,-125,-32,66,0,62,0,34,0,19,-64,10,0,10,0,6,0,3,-32,0,0,0,0,0,0},
		{4,0,8,0,30,0,32,0,64,0,64,0,64,0,64,0,64,0,32,0,30,0,0,0,0,0,0,0},
		{0,0,0,0,126,0,64,0,64,0,64,0,124,0,64,0,64,0,64,0,126,0,0,0,8,0,16,0},
		{0,0,0,0,126,0,64,0,64,0,64,0,124,0,64,0,64,0,64,0,126,0,0,0,16,0,8,0},
		{0,0,0,0,126,0,64,0,64,0,64,0,124,0,64,0,64,0,64,0,126,0,0,0,20,0,8,0},
		{0,0,0,0,126,0,64,0,64,0,64,0,124,0,64,0,64,0,64,0,126,0,0,0,20,0,0,0},
		{0,0,0,0,64,0,64,0,64,0,64,0,64,0,64,0,64,0,64,0,64,0,0,0,64,0,-128,0},
		{0,0,0,0,64,0,64,0,64,0,64,0,64,0,64,0,64,0,64,0,64,0,0,0,64,0,32,0},
		{0,0,0,0,64,0,64,0,64,0,64,0,64,0,64,0,64,0,64,0,64,0,0,0,-96,0,64,0},
		{0,0,0,0,64,0,64,0,64,0,64,0,64,0,64,0,64,0,64,0,64,0,0,0,-96,0,0,0},
		{0,0,0,0,124,0,66,0,65,0,65,0,-15,0,65,0,65,0,66,0,124,0,0,0,0,0,0,0},
		{0,0,0,0,65,0,67,0,69,0,69,0,73,0,81,0,81,0,97,0,65,0,0,0,22,0,26,0},
		{0,0,0,0,28,0,34,0,65,0,65,0,65,0,65,0,65,0,34,0,28,0,0,0,4,0,8,0},
		{0,0,0,0,28,0,34,0,65,0,65,0,65,0,65,0,65,0,34,0,28,0,0,0,8,0,4,0},
		{0,0,0,0,28,0,34,0,65,0,65,0,65,0,65,0,65,0,34,0,28,0,0,0,20,0,8,0},
		{0,0,0,0,28,0,34,0,65,0,65,0,65,0,65,0,65,0,34,0,28,0,0,0,22,0,26,0},
		{0,0,0,0,28,0,34,0,65,0,65,0,65,0,65,0,65,0,34,0,28,0,0,0,20,0,0,0},
		{0,0,0,0,65,0,34,0,20,0,8,0,20,0,34,0,65,0,0,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,92,0,34,0,81,0,81,0,73,0,69,0,69,0,34,0,29,0,0,0,0,0,0,0},
		{0,0,0,0,60,0,66,0,66,0,66,0,66,0,66,0,66,0,66,0,66,0,0,0,8,0,16,0},
		{0,0,0,0,60,0,66,0,66,0,66,0,66,0,66,0,66,0,66,0,66,0,0,0,16,0,8,0},
		{0,0,0,0,60,0,66,0,66,0,66,0,66,0,66,0,66,0,66,0,66,0,0,0,20,0,8,0},
		{0,0,0,0,60,0,66,0,66,0,66,0,66,0,66,0,66,0,66,0,66,0,0,0,20,0,0,0},
		{0,0,0,0,16,0,16,0,16,0,16,0,16,0,40,0,40,0,68,0,-126,0,0,0,16,0,8,0},
		{0,0,0,0,64,0,64,0,120,0,68,0,68,0,68,0,120,0,64,0,64,0,0,0,0,0,0,0},
		{0,0,0,0,88,0,68,0,68,0,72,0,80,0,80,0,72,0,72,0,48,0,0,0,0,0,0,0},
		{0,0,0,0,62,0,68,0,68,0,60,0,4,0,68,0,56,0,0,0,8,0,16,0,0,0,0,0},
		{0,0,0,0,62,0,68,0,68,0,60,0,4,0,68,0,56,0,0,0,32,0,16,0,0,0,0,0},
		{0,0,0,0,62,0,68,0,68,0,60,0,4,0,68,0,56,0,0,0,40,0,16,0,0,0,0,0},
		{0,0,0,0,62,0,68,0,68,0,60,0,4,0,68,0,56,0,0,0,44,0,52,0,0,0,0,0},
		{0,0,0,0,62,0,68,0,68,0,60,0,4,0,68,0,56,0,0,0,40,0,0,0,0,0,0,0},
		{0,0,0,0,62,0,68,0,68,0,60,0,4,0,68,0,56,0,0,0,28,0,20,0,28,0,0,0},
		{0,0,0,0,55,-128,72,0,72,0,63,-128,8,-128,72,-128,55,0,0,0,0,0,0,0,0,0,0,0},
		{8,0,16,0,56,0,64,0,64,0,64,0,64,0,64,0,56,0,0,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,60,0,64,0,64,0,124,0,68,0,68,0,56,0,0,0,8,0,16,0,0,0,0,0},
		{0,0,0,0,60,0,64,0,64,0,124,0,68,0,68,0,56,0,0,0,16,0,8,0,0,0,0,0},
		{0,0,0,0,60,0,64,0,64,0,124,0,68,0,68,0,56,0,0,0,40,0,16,0,0,0,0,0},
		{0,0,0,0,60,0,64,0,64,0,124,0,68,0,68,0,56,0,0,0,40,0,0,0,0,0,0,0},
		{0,0,0,0,64,0,64,0,64,0,64,0,64,0,64,0,64,0,0,0,64,0,-128,0,0,0,0,0},
		{0,0,0,0,64,0,64,0,64,0,64,0,64,0,64,0,64,0,0,0,64,0,32,0,0,0,0,0},
		{0,0,0,0,64,0,64,0,64,0,64,0,64,0,64,0,64,0,0,0,-96,0,64,0,0,0,0,0},
		{0,0,0,0,64,0,64,0,64,0,64,0,64,0,64,0,64,0,0,0,-96,0,0,0,0,0,0,0},
		{0,0,0,0,56,0,68,0,68,0,68,0,68,0,68,0,56,0,40,0,112,0,8,0,0,0,0,0},
		{0,0,0,0,68,0,68,0,68,0,68,0,68,0,100,0,88,0,0,0,44,0,52,0,0,0,0,0},
		{0,0,0,0,56,0,68,0,68,0,68,0,68,0,68,0,56,0,0,0,16,0,32,0,0,0,0,0},
		{0,0,0,0,56,0,68,0,68,0,68,0,68,0,68,0,56,0,0,0,16,0,8,0,0,0,0,0},
		{0,0,0,0,56,0,68,0,68,0,68,0,68,0,68,0,56,0,0,0,40,0,16,0,0,0,0,0},
		{0,0,0,0,56,0,68,0,68,0,68,0,68,0,68,0,56,0,0,0,44,0,52,0,0,0,0,0},
		{0,0,0,0,56,0,68,0,68,0,68,0,68,0,68,0,56,0,0,0,40,0,0,0,0,0,0,0},
		{0,0,0,0,8,0,0,0,0,0,127,0,0,0,0,0,8,0,0,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,120,0,68,0,100,0,84,0,76,0,68,0,60,0,0,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,52,0,76,0,68,0,68,0,68,0,68,0,68,0,0,0,16,0,32,0,0,0,0,0},
		{0,0,0,0,52,0,76,0,68,0,68,0,68,0,68,0,68,0,0,0,16,0,8,0,0,0,0,0},
		{0,0,0,0,52,0,76,0,68,0,68,0,68,0,68,0,68,0,0,0,40,0,16,0,0,0,0,0},
		{0,0,0,0,52,0,76,0,68,0,68,0,68,0,68,0,68,0,0,0,40,0,0,0,0,0,0,0},
		{32,0,16,0,16,0,40,0,40,0,68,0,68,0,-126,0,-126,0,0,0,16,0,8,0,0,0,0,0},
		{64,0,64,0,92,0,98,0,66,0,66,0,66,0,98,0,92,0,64,0,64,0,0,0,0,0,0,0},
		{32,0,16,0,16,0,40,0,40,0,68,0,68,0,-126,0,-126,0,0,0,40,0,0,0,0,0,0,0},
	};
	
	/**
	 * The AdvanceX value for each character (autogenerated from
	 * default "Sans Serif" 14 font).
	 */
	static final float[] fontAdvance = new float[] {
		9,9,9,9,9,9,9,9,9,0,0,9,9,0,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,
		4,4,4,8,8,8,8,3,4,4,6,10,4,7,4,6,8,8,8,8,8,8,8,8,8,8,4,4,10,10,10,5,
		10,8,7,8,9,7,6,9,9,3,4,8,6,10,9,9,7,9,8,6,8,8,8,10,8,7,7,4,6,4,8,6,
		7,7,8,6,8,7,4,7,7,3,4,7,3,11,7,7,8,8,5,6,4,7,6,9,7,6,7,4,4,4,8,9,
		9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,
		4,4,8,8,8,8,4,8,7,10,6,6,10,7,8,6,5,10,5,5,7,8,8,4,7,5,6,6,10,10,10,5,
		8,8,8,8,8,8,11,8,7,7,7,7,3,3,3,3,9,9,9,9,9,9,9,10,9,8,8,8,8,7,7,7,
		7,7,7,7,7,7,10,6,7,7,7,7,3,3,3,3,7,7,7,7,7,7,7,10,7,7,7,7,7,6,8,6
	};
	
	static class MultisampleChooser extends DefaultGLCapabilitiesChooser {
	    public int chooseCapabilities(GLCapabilities desired,
	                                  GLCapabilities[] available,
	                                  int windowSystemRecommendedChoice) {
	      boolean anyHaveSampleBuffers = false;
	      for (int i = 0; i < available.length; i++) {
	        GLCapabilities caps = available[i];
	        if (caps != null && caps.getSampleBuffers()) {
	          anyHaveSampleBuffers = true;
	          break;
	        }
	      }
	      int selection = super.chooseCapabilities(desired, available, windowSystemRecommendedChoice);
	      if (!anyHaveSampleBuffers) {
	        System.err.println("WARNING: antialiasing will be disabled because none of the available pixel formats had it to offer");
	      } else {
	        if (!available[selection].getSampleBuffers()) {
	          System.err.println("WARNING: antialiasing will be disabled because the DefaultGLCapabilitiesChooser didn't supply it");
	        }
	      }
	      return selection;
	    }
	  }
	
	private final static float BONE_LENGTH = 1.0f;
	private final static float BONE_WIDTH = 0.1f;
	private final static GlMaterial BONE_MATERIAL = new GlMaterial(new Color3f(), 0.25f, 0.0f, 10);
	
	private final static Shape BONE = new Shape(
			new Point3f[] {
					new Point3f(0, 0, 0),
					new Point3f(BONE_WIDTH, 0, BONE_WIDTH),
					new Point3f(0, BONE_WIDTH, BONE_WIDTH),
					new Point3f(-BONE_WIDTH, 0, BONE_WIDTH),
					new Point3f(0,-BONE_WIDTH, BONE_WIDTH),
					new Point3f(0, 0, BONE_LENGTH),
			},
			new int[] { 0, 2, 1, 0, 3, 2, 0, 4, 3, 0, 1, 4, 5, 1, 2, 5, 2, 3, 5, 3, 4, 5, 4, 1 }
	);
	
	/** Offset to the GL Display-Lists holding the character bitmaps. */
	private int fontOffset;
	
	private int maxLights, maxTextureSize;
	
	GLEventListener glEventListener;
	
	private static final int QUAD_BUFFER_SIZE = 64;
	private final FloatBuffer buffer = BufferUtil.newFloatBuffer(4 * 12 * QUAD_BUFFER_SIZE);
	
	public ViewportGl(int id, ViewDirection direction, CollectionAttr<ViewDirection> orthoDirections, JPatchInspector inspector) {
		super(id, direction, orthoDirections, inspector);
		
//		GLCapabilities caps = new GLCapabilities();
//	    GLCapabilitiesChooser chooser = new MultisampleChooser();
//
//	    caps.setSampleBuffers(antialiasAttr.getBoolean());
//	   
//	    caps.setNumSamples(4);
//	    drawable = new GLCanvas(caps, chooser, null, null);
	    
	    drawable = new GLCanvas();
//		drawable = LIGHTWEIGHT ? new GLJPanel(caps) : new GLCanvas(caps);
		component = (Component) drawable;
		component.setBackground(COLORS.background.get());
		
		glEventListener = new GLEventListener() {

			public void init(GLAutoDrawable drawable) {
//				System.out.println("GL init");
				drawable.setGL(new DebugGL(drawable.getGL()));
				GL gl = drawable.getGL();
//				gl.glEnd();
				
				/* Generate display lists to render font characters. */
				gl.glPixelStorei(GL.GL_UNPACK_ALIGNMENT, 1);
				fontOffset = gl.glGenLists(256);
				for (int i = 0; i < 256; i++) {
			        gl.glNewList(i + fontOffset, GL_COMPILE);
			            gl.glBitmap(16, 12, 0, 0, fontAdvance[i], 0, fontRaster[i], 0);
			        gl.glEndList();
			    }
				
				/* retrieve GL_MAX_LIGHTS and GL_MAX_TEXTURE_SIZE */
				int[] I = new int[1];
				gl.glGetIntegerv(GL_MAX_LIGHTS, I, 0);
				maxLights = I[0];
				gl.glGetIntegerv(GL_MAX_TEXTURE_SIZE, I, 0);
				maxTextureSize = I[0];
				
				setLighting(RealtimeLighting.createThreepointLight());	
				gl.glLightModelf(GL_LIGHT_MODEL_TWO_SIDE, 1);
//				gl.glLightModelf(GL_LIGHT_MODEL_COLOR_CONTROL, GL_SEPARATE_SPECULAR_COLOR);
//				setLighting(RealtimeLighting.createHeadLight());
				
//				gl.glHint(GL_MULTISAMPLE_FILTER_HINT_NV, GL_NICEST);
				
				
				gl.glEnable(GL_POLYGON_OFFSET_FILL);
				gl.glPolygonOffset(1.0f, 1.0f);
				gl.glDisable(GL_DEPTH_TEST);
				gl.glDisable(GL_NORMALIZE);
				gl.glDisable(GL_CULL_FACE);
//				gl.glPolygonMode(GL_FRONT, GL_LINE);
//				gl.glCullFace(GL_NONE);
//				gl.glFrontFace(GL_CW);	// left handed
				canUseProgram = gl.isFunctionAvailable("glUseProgram");
				canUseProgram = false;
				if (canUseProgram) {
					int vertexShader = gl.glCreateShader(GL_VERTEX_SHADER);
					try {
						loadShader(ClassLoader.getSystemResourceAsStream("glsl/perPixelLight.vs"), gl, vertexShader);
					} catch (IOException e) {
						e.printStackTrace();
					}
					gl.glCompileShader(vertexShader);
					printShaderInfo(gl, vertexShader);
					
					int fragmentShader = gl.glCreateShader(GL_FRAGMENT_SHADER);
					try {
						loadShader(ClassLoader.getSystemResourceAsStream("glsl/perPixelLight.fs"), gl, fragmentShader);
					} catch (IOException e) {
						e.printStackTrace();
					}
					gl.glCompileShader(fragmentShader);
					printShaderInfo(gl, fragmentShader);
					
					program = gl.glCreateProgram();
					gl.glAttachShader(program, vertexShader);
					gl.glAttachShader(program, fragmentShader);
					gl.glLinkProgram(program);
					gl.glUseProgram(program);
					printProgramInfo(gl, program);
//					gl.glUseProgram(0);
				}
//				canUseProgram = false;
				
				int[] tex = new int[1];
				gl.glGenTextures(0, tex, 0);
				screenshotTexture = tex[0];
				
				depthBuffer = BufferUtil.newFloatBuffer(component.getWidth() * component.getHeight());
				System.out.println("component dimension = " + component.getWidth() + "x" + component.getHeight());
				System.out.println("depth buffer capacity = " + depthBuffer.capacity());
				
				BACK_MATERIAL.getGlMaterial().applyMaterial(gl, GL_BACK);
				
			}

			public void display(GLAutoDrawable drawable) {
				GL gl = drawable.getGL();
//				System.out.println("GL display " + this + " " + repaintCount++);
//				long t = System.currentTimeMillis();
//				gl.glFlush();
//				gl.glFinish();	// wait for previous gl functions to finish
				Color3f background = true ? COLORS.activeBackground : COLORS.background;
				gl.glClearColor(background.x, background.y, background.z, 0);	// set background color
//				gl.glClearColor(1, 0.5f, 0, 0);
//				gl.glClearDepth(farClip);									// set initial depth-buffer value
				gl.glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);	// clear color and depth buffers
//				gl.glFlush();
//				gl.glFinish();
				draw();
//				gl.glFlush();
//				gl.glFinish();
//				System.out.println("GL display on thread " + Thread.currentThread());
//				System.out.println(System.currentTimeMillis() - t);
			}

			public void reshape(GLAutoDrawable drawable, int x, int y, int width, int height) {
//				System.out.println("GL reshape");
				
//				viewDef.computeMatrix();
//				init(drawable);
//				display(drawable);
				
//				depthBuffer = BufferUtil.newFloatBuffer(component.getWidth() * component.getHeight());
//				System.out.println("component dimension = " + component.getWidth() + "x" + component.getHeight());
//				System.out.println("depth buffer capacity = " + depthBuffer.capacity());
				init(drawable);
				
			}

			public void displayChanged(GLAutoDrawable drawable, boolean modeChanged, boolean deviceChanged) {
//				System.out.println("GL displayChanged");
			}
		};
		
		drawable.addGLEventListener(glEventListener);
		
//		component.addMouseWheelListener(new MouseWheelListener() {
//			public void mouseWheelMoved(MouseWheelEvent e) {
//				subdivLevel += e.getWheelRotation();
//				if (subdivLevel < 1) subdivLevel = 1;
//				if (subdivLevel > 6) subdivLevel = 6;
//				
//				useProgram = !useProgram;
//
//				component.repaint();
//			}
//		});
	}
	
//	public void display() {
//		drawable.
//	}

	public GL getGl() {
		return drawable.getGL();
	}
	
//	@Override
//	public void drawShape(Shape s) {
//		gl.glShadeModel(GL_SMOOTH);
//		gl.glEnable(GL_LIGHTING);
//		gl.glBegin(GL_TRIANGLES);
//		for (int i = 0, n = s.meshes.length; i < n; i++) {
//			drawTriangleMesh(s.meshes[i]);
//		}
//		gl.glEnd();
//		gl.glDisable(GL_LIGHTING);
//		gl.glEnable(GL_LINE_SMOOTH);
//		gl.glEnable(GL_BLEND);
//		gl.glBegin(GL_LINES);
//		for (int i = 0, n = s.wires.length; i < n; i++) {
//			drawWireFrame(s.wires[i]);
//		}
//		gl.glEnd();
//		gl.glDisable(GL_BLEND);
//		gl.glDisable(GL_LINE_SMOOTH);
//	}
	
	public void setMaterial(int side, float[] array) {
		GL gl = drawable.getGL();
		gl.glMaterialfv(side, GL_AMBIENT, array, GlMaterial.AMBIENT);
		gl.glMaterialfv(side, GL_DIFFUSE, array, GlMaterial.DIFFUSE);
		gl.glMaterialfv(side, GL_SPECULAR, array, GlMaterial.SPECULAR);
		gl.glMaterialfv(side, GL_EMISSION, array, GlMaterial.EMISSION);
		gl.glMaterialfv(side, GL_SHININESS, array, GlMaterial.SHININESS);
//		BACK_MATERIAL.getGlMaterial().applyMaterial(gl, GL_BACK);
	}
	
//	private void drawTriangleMesh(TriangleMesh t) {
//		setMaterial(GL_FRONT, t.m.getArray());
//		Matrix4d matrix = viewDef.getMatrix();
//		
//		for (int i = 0, n = t.t.length; i < n; i++) {
//			p.set(t.v[t.t[i]]);
//			v.set(t.n[t.t[i]]);
//			matrix.transform(p);
//			matrix.transform(v);
//			v.normalize();
//			gl.glNormal3f(v.x, v.y, v.z);
//			gl.glVertex3f(p.x, p.y, p.z);
//		}
//	}
//	
//	private void drawWireFrame(WireFrame w) {
//		gl.glColor4fv(w.array, 0);
//		Matrix4d matrix = viewDef.getMatrix();
//		for (int i = 0, n = w.l.length; i < n; i++) {
//			p.set(w.v[w.l[i]]);
//			matrix.transform(p);
//			gl.glVertex3f(p.x, p.y, p.z);
//		}
//	}
	
	@Override
	public void draw() {
		screenshotTextureValid = false;
		depthBufferValid = false;
		GL gl = drawable.getGL();

		
//		if (antialiasAttr.getBoolean()) {
//			gl.glEnable(GL_MULTISAMPLE);
//		} else {
//			gl.glDisable(GL_MULTISAMPLE);
//		}
		viewDef.configureTransformUtil(transformUtil);
		time = System.nanoTime();
//		System.out.println("ViewportGL.draw() at " + System.currentTimeMillis());
//		if (true) return;
//		rasterMode();
//		drawGrid();
		spatialMode();
//		gl.glPolygonMode(GL_FRONT_AND_BACK, GL_LINE);
//		gl.glColor3f(0, 0, 0);
		gl.glShadeModel(GL_SMOOTH);
//		gl.glDisable(GL_COLOR_MATERIAL);
//		gl.glEnable(GL_LIGHTING);
		gl.glEnable(GL_NORMALIZE);
		
//		if (true) return;
		
//		gl.glEnable(GL_BLEND);
//		Matrix4d m = new Matrix4d();
//		TriangleMesh cx = TriangleMesh.createCone(16, new GlMaterial(new Color3f(0.4f, 0, 0), new Color3f(0.8f, 0, 0), new Color3f(0, 0, 0), 0));
//		TriangleMesh cy = TriangleMesh.createCone(16, new GlMaterial(new Color3f(0, 0.4f, 0), new Color3f(0, 0.8f, 0), new Color3f(0, 0, 0), 0));
//		TriangleMesh cz = TriangleMesh.createCone(16, new GlMaterial(new Color3f(0.2f, 0.2f, 0.4f), new Color3f(0.4f, 0.4f, 0.8f), new Color3f(0, 0, 0), 0));
//		m.set(new double[] {
//				0, 0, 0.2, 0.9,
//				0, 0.2, 0, 0,
//				0.2, 0, 0, 0,
//				0, 0, 0, 1
//		});
//		cx.transform(m);
//		m.set(new double[] {
//				0.2, 0, 0, 0,
//				0, 0, 0.2, 0.9,
//				0, 0.2, 0, 0,Matrix4f
//				0, 0, 0, 1
//		});
//		cy.transform(m);
//		m.set(new double[] {
//				0.2, 0, 0, 0,
//				0, 0.2, 0, 0,
//				0, 0, 0.2, 0.9,
//				0, 0, 0, 1
//		});
//		cz.transform(m);
//		WireFrame wx = new WireFrame(new Point3d[] { new Point3d(0, 0, 0), new Point3d(1, 0, 0) }, new int[] { 0, 1 }, new Color3f(1, 0, 0));
//		WireFrame wy = new WireFrame(new Point3d[] { new Point3d(0, 0, 0), new Point3d(0, 1, 0) }, new int[] { 0, 1 }, new Color3f(0, 1, 0));
//		WireFrame wz = new WireFrame(new Point3d[] { new Point3d(0, 0, 0), new Point3d(0, 0, 1) }, new int[] { 0, 1 }, new Color3f(0.5f, 0.5f, 1));
//		
//		Shape s = new Shape(new TriangleMesh[] { cx, cy, cz }, new WireFrame[] { wx, wy, wz } );
		
//		drawShape(s);
		
//		for (Model model : models) {
//			drawModel(model);
//		}
		
//		gl.glPolygonMode(GL_FRONT, GL_LINE);
//		drawSds(Main.getInstance().getActiveSds());
//		Sds activeSds = Main.getInstance().getActiveSds();
//		if (activeSds != null) {
//			drawSds3(activeSds);
//		}
		
//		Matrix4d cameraMatrix = viewDef.getMatrix(new Matrix4d());	// TODO: write better implementation 
//		transformUtil.setCamera2World(cameraMatrix);
		
//		drawOrigin(viewDef.getTransformUtil().getMatrix(WORLD, CAMERA, new Matrix4f()));
		
		gl.glLineWidth(1);
		SceneGraphNode sceneGraphRoot = Main.getInstance().getSceneGraphRoot();
		drawSceneGraphElement(sceneGraphRoot);
//		Selection selection = Main.getInstance().getSelection();
		
//		gl.glDisable(GL_LIGHTING);
//		drawSelection(selection, new Color3f(1, 1, 0));
		
		JPatchTool tool = Main.getInstance().getActiveTool();
//		System.out.println("tool = " + tool);
		gl.glMatrixMode(GL_MODELVIEW);
		gl.glLoadIdentity();
		if (tool != null) {
			tool.draw(this);
		}
		rasterMode();
		if (showNodeNamesAttr.getBoolean()) {
			drawSceneGraphNames(sceneGraphRoot);
		}
		drawInfo();
//		gl.glFlush(); // ensure that everything gets drawn
//		gl.glFinish();
		lastRedrawTime = System.currentTimeMillis();
	}
	
	public long getContentAge() {
		return System.currentTimeMillis() - lastRedrawTime;
	}
	
	private void drawSceneGraphElement(SceneGraphNode node) {
		GL gl = drawable.getGL();
		
//		System.out.println("drawing " + node + " " + (node == null ? "(null)" : "(not null)"));
//		Matrix4d matrix = new Matrix4d(viewDef.getMatrix(new Matrix4d()));
//		Transform transform = node.getTransform();
		
		if (node instanceof XFormNode) {
			((XFormNode) node).getLocal2WorldTransform(transformUtil, LOCAL);
		} else {
			transformUtil.setSpace2World(TransformUtil.LOCAL, IDENTITY);
		}
		
//		for (int i = 0; i < 4; i++) {
//			for (int j = 0; j < 4; j++) {
//				System.out.print(modelView[i + j * 4] + " \t");
//			}
//			System.out.println();
//		}
//		System.out.println();
		
//		if (transform != null) {
//			transformUtil.setTransform(LOCAL, transform);
////			transform.mul2(matrix);
////			transform.getMatrix(m);
////			if (node instanceof TransformNode) {
////				System.out.println("sceneGraph TransformNode @ " + ((TransformNode) node).getNameAttribute().getValue());
////				System.out.println(modelViewMatrix);
////			}
////			modelViewMatrix.set(matrix);
////			matrix.mul(m);
////			m.mul(matrix);
////			matrix.mul(m);
////			modelViewMatrix.mul(matrix);
//		} else {
//			transformUtil.setSpace2World(TransformUtil.LOCAL, IDENTITY);
//		}
//		modelView.set(matrix);
		
		transformUtil.getMatrix(TransformUtil.LOCAL, TransformUtil.CAMERA, modelView);
		gl.glMatrixMode(GL_MODELVIEW);
		gl.glLoadMatrixd(modelView, 0);
		
		drawOrigin();
		if (node instanceof SdsModel) {
			Sds sds = ((SdsModel) node).getSds();
			drawSds2(
				sds,
				showControlMeshAttr.getBoolean(),
				showLimitSurfaceAttr.getBoolean(),
				showProjectedMeshAttr.getBoolean(),
				sds.getRenderLevelAttribute().getInt(),
				sds.getEditLevelAttribute().getInt(),
				LINE_COLOR,
				LINE_MATERIAL.getGlMaterial()
			);
		}
		if (node instanceof Bone) {
			Bone bone = (Bone) node;
			double length = bone.getLengthAttribute().getDouble();
			modelView[0] *= length;
			modelView[1] *= length;
			modelView[2] *= length;
			modelView[4] *= length;
			modelView[5] *= length;
			modelView[6] *= length;
			modelView[8] *= length;
			modelView[9] *= length;
			modelView[10] *= length;
			Color3f color = bone.getColor(new Color3f()); // TODO reuse color object
			gl.glEnable(GL_LIGHTING);
			gl.glShadeModel(GL_SMOOTH);
			gl.glPolygonMode(GL_FRONT, GL_FILL);
			gl.glColor3f(0, 0, 0);
//			gl.glDisable(GL_COLOR_MATERIAL);
			color.scale(0.8f);
			BONE_MATERIAL.setKd(color);
			color.scale(0.25f);
			BONE_MATERIAL.setKa(color);
			BONE_MATERIAL.applyMaterial(gl, GL_FRONT);
			BONE.draw(gl);
			gl.glEnable(GL_DEPTH_TEST);
		}
		for (SceneGraphNode child : node.getChildrenAttribute().getElements()) {
			drawSceneGraphElement(child);
		}
		
	}
	
	public void setModelViewMatrix(XFormNode node) {
		node.getLocal2WorldTransform(transformUtil, TransformUtil.LOCAL);
		setModelViewMatrix(transformUtil);
	}
	
	public void setModelViewMatrix(TransformUtil transformUtil) {
		GL gl = drawable.getGL();
		transformUtil.getMatrix(TransformUtil.LOCAL, TransformUtil.CAMERA, modelView);
		gl.glMatrixMode(GL_MODELVIEW);
		gl.glLoadMatrixd(modelView, 0);
	}
	
	private void drawSceneGraphNames(SceneGraphNode node) {
		if (node instanceof XFormNode) {
			((XFormNode) node).getLocal2WorldTransform(transformUtil, LOCAL);
		} else {
			transformUtil.setSpace2World(TransformUtil.LOCAL, IDENTITY);
		}
		Point3d p = new Point3d();
		transformUtil.projectToScreen(LOCAL, p, p);
		if (node instanceof XFormNode) {
			if (!transformUtil.isPerspective() || p.z > nearClip) {
				drawString(((XFormNode) node).getNameAttribute().getValue(), (int) p.x, (int) p.y);
			}
		}
		for (SceneGraphNode child : node.getChildrenAttribute().getElements()) {
			drawSceneGraphNames(child);
		}
	}
	
//	public void setMaterial(Color3f ka) {
//		gl.glMaterialfv(side, GL_AMBIENT, new float[] { mp.red * mp.ambient, mp.green * mp.ambient, mp.blue * mp.ambient, 1 } );
//		gl.glMaterialfv(side, GL_DIFFUSE, new float[] { mp.red * mp.diffuse, mp.green * mp.diffuse, mp.blue * mp.diffuse, 1 } );
//		gl.glMaterialfv(side, GL_SPECULAR, new float[] {
//				mp.specular * (1 - mp.metallic + mp.metallic * mp.red),
//				mp.specular * (1 - mp.metallic + mp.metallic * mp.green),
//				mp.specular * (1 - mp.metallic + mp.metallic * mp.blue),
//				1.0f });
//		gl.glMaterialfv(side, GL_SHININESS, new float[] { 1f / mp.roughness } );
//	}
	
	public void setLighting(RealtimeLighting lighting) {
		GL gl = drawable.getGL();
		Color3f ambient = lighting.getAmbientColor();
		gl.glLightModelfv(GL_LIGHT_MODEL_AMBIENT, new float[] { ambient.x, ambient.y, ambient.z, 1 }, 0);
		for (int i = 0; i < maxLights; i++) {
			if (i < lighting.numLights()) {
				gl.glEnable(GL_LIGHT0 + i);
				RealtimeLighting.LightSource light = lighting.getLight(i);
				if (light instanceof RealtimeLighting.DirectionalLight) {
					RealtimeLighting.DirectionalLight directionalLight = (RealtimeLighting.DirectionalLight) light;
					Color3f color = directionalLight.getColor();
					
					/*
					 * set GL light colors
					 */
					gl.glLightfv(GL_LIGHT0 + i, GL_AMBIENT, new float[] { 0, 0, 0, 1 }, 0);
					gl.glLightfv(GL_LIGHT0 + i, GL_DIFFUSE, new float[] { color.x, color.y, color.z, 1 }, 0);
					if (directionalLight.castsHighlight())
						gl.glLightfv(GL_LIGHT0 + i, GL_SPECULAR, new float[] { color.x, color.y, color.z, 1 }, 0);
					else
						gl.glLightfv(GL_LIGHT0 + i, GL_SPECULAR, new float[] { 0, 0, 0, 1 }, 0);
					Vector3f direction = directionalLight.getTransformedDirection();
					
					/*
					 * set GL light directions (w = 0 for directional light)
					 */
					gl.glLightfv(GL_LIGHT0 + i, GL_POSITION, new float[] { direction.x, direction.y, direction.z, 0 }, 0);
					
					/*
					 * set GL spot cutoff (180 = no spot)
					 */
					gl.glLightf(GL_LIGHT0 + i, GL_SPOT_CUTOFF, 180);
				} else if (light instanceof RealtimeLighting.PointLight) {
					RealtimeLighting.PointLight pointLight = (RealtimeLighting.PointLight) light;
					Color3f color = pointLight.getColor();
					
					/*
					 * set GL light colors
					 */
					gl.glLightfv(GL_LIGHT0 + i, GL_AMBIENT, new float[] { 0, 0, 0, 1 }, 0);
					gl.glLightfv(GL_LIGHT0 + i, GL_DIFFUSE, new float[] { color.x, color.y, color.z, 1 }, 0);
					if (pointLight.castsHighlight())
						gl.glLightfv(GL_LIGHT0 + i, GL_SPECULAR, new float[] { color.x, color.y, color.z, 1 }, 0);
					else
						gl.glLightfv(GL_LIGHT0 + i, GL_SPECULAR, new float[] { 0, 0, 0, 1 }, 0);
					Point3f position = pointLight.getTransformedPosition();
					
					/*
					 * set GL light position (w = 1 for point light)
					 */
					gl.glLightfv(GL_LIGHT0 + i, GL_POSITION, new float[] { position.x, position.y, position.z, 1 }, 0);
					
					/*
					 * set GL attenuation
					 */
					switch (pointLight.getAttenuation()) {
						case 0: {
							gl.glLightf(GL_LIGHT0 + i, GL_CONSTANT_ATTENUATION, 1);
							gl.glLightf(GL_LIGHT0 + i, GL_LINEAR_ATTENUATION, 0);
							gl.glLightf(GL_LIGHT0 + i, GL_QUADRATIC_ATTENUATION, 0);
						} break;
						case 1: {
							gl.glLightf(GL_LIGHT0 + i, GL_CONSTANT_ATTENUATION, 0);
							gl.glLightf(GL_LIGHT0 + i, GL_LINEAR_ATTENUATION, 1f / pointLight.getDistance());
							gl.glLightf(GL_LIGHT0 + i, GL_QUADRATIC_ATTENUATION, 0);
						} break;
						case 2: {
							gl.glLightf(GL_LIGHT0 + i, GL_CONSTANT_ATTENUATION, 0);
							gl.glLightf(GL_LIGHT0 + i, GL_LINEAR_ATTENUATION, 0);
							gl.glLightf(GL_LIGHT0 + i, GL_QUADRATIC_ATTENUATION, 1f / pointLight.getDistance() / pointLight.getDistance());
						} break;
					}
					
					/*
					 * set GL spot cutoff (180 = no spot)
					 */
					gl.glLightf(GL_LIGHT0 + i, GL_SPOT_CUTOFF, 180);
				} else if (light instanceof RealtimeLighting.SpotLight) {
					RealtimeLighting.SpotLight spotLight = (RealtimeLighting.SpotLight) light;
					Color3f color = spotLight.getColor();
					
					/*
					 * set GL light colors
					 */
					gl.glLightfv(GL_LIGHT0 + i, GL_AMBIENT, new float[] { 0, 0, 0, 1 }, 0);
					gl.glLightfv(GL_LIGHT0 + i, GL_DIFFUSE, new float[] { color.x, color.y, color.z, 1 }, 0);
					if (spotLight.castsHighlight())
						gl.glLightfv(GL_LIGHT0 + i, GL_SPECULAR, new float[] { color.x, color.y, color.z, 1 }, 0);
					else
						gl.glLightfv(GL_LIGHT0 + i, GL_SPECULAR, new float[] { 0, 0, 0, 1 }, 0);
					Point3f position = spotLight.getTransformedPosition();
					
					/*
					 * set GL light position (w = 1 for point light)
					 */
					gl.glLightfv(GL_LIGHT0 + i, GL_POSITION, new float[] { position.x, position.y, position.z, 1 }, 0);
					
					/*
					 * set GL attenuation
					 */
					switch (spotLight.getAttenuation()) {
						case 0: {
							gl.glLightf(GL_LIGHT0 + i, GL_CONSTANT_ATTENUATION, 1);
							gl.glLightf(GL_LIGHT0 + i, GL_LINEAR_ATTENUATION, 0);
							gl.glLightf(GL_LIGHT0 + i, GL_QUADRATIC_ATTENUATION, 0);
						} break;
						case 1: {
							gl.glLightf(GL_LIGHT0 + i, GL_CONSTANT_ATTENUATION, 0);
							gl.glLightf(GL_LIGHT0 + i, GL_LINEAR_ATTENUATION, 1f / spotLight.getDistance());
							gl.glLightf(GL_LIGHT0 + i, GL_QUADRATIC_ATTENUATION, 0);
						} break;
						case 2: {
							gl.glLightf(GL_LIGHT0 + i, GL_CONSTANT_ATTENUATION, 0);
							gl.glLightf(GL_LIGHT0 + i, GL_LINEAR_ATTENUATION, 0);
							gl.glLightf(GL_LIGHT0 + i, GL_QUADRATIC_ATTENUATION, 1f / spotLight.getDistance() / spotLight.getDistance());
						} break;
					}
					
					Vector3f direction = spotLight.getTransformedDirection();
					
					/*
					 * set GL spot direction
					 */
					gl.glLightfv(GL_LIGHT0 + i, GL_SPOT_DIRECTION, new float[] { direction.x, direction.y, direction.z }, 0);
					
					/*
					 * set GL spot cutoff
					 */
					gl.glLightf(GL_LIGHT0 + i, GL_SPOT_CUTOFF, spotLight.getRadius());
					
					/*
					 * set GL spot cutoff exponent
					 */
					gl.glLightf(GL_LIGHT0 + i, GL_SPOT_EXPONENT, 0);
				}
			} else {
				gl.glDisable(GL_LIGHT0 + i);
			}
		}
	}
	
//	@Override
//	protected void drawGrid() {
//		double scale = viewTypeAttr.getValue()..getDouble();
//		double width = component.getWidth();
//		double height = component.getHeight();
//		double matrixScale = scale / 20 * width;
//		double u = 1000 / scale / width;
//		double majorSpacing = (float) Math.pow(10, Math.floor(Math.log10(u)));
//		double screenSpacing = majorSpacing * matrixScale;
//		double xCenter = (float) matrix.m03 + width / 2;
//		double yCenter = (float) matrix.m13 + height / 2;
//		float r = COLORS.majorGrid.x;
//		float g = COLORS.majorGrid.y;
//		float b = COLORS.majorGrid.z;
////		float r0 = COLORS.minorGrid.x;
////		float g0 = COLORS.minorGrid.y;
////		float b0 = COLORS.minorGrid.z;
//		float a;
////		System.out.println("majorSpacing=" + majorSpacing + " screenSpacing=" + screenSpacing);
//		
//		gl.glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA);
//		gl.glEnable(GL_BLEND);
//		gl.glBegin(GL_LINES);
//		
//		double spacing;
////		System.out.println("screenSpacing=" + screenSpacing);
//		for (int pass = 0; pass < 3; pass++) {
//			switch(pass) {
//			case 0:
//				spacing = screenSpacing / 2; // 2.5 - 25
//				a = (float) (Math.min(1, Math.max(0, (spacing - 5) / 2)) * 0.5 +
//					Math.min(1, Math.max(0, (spacing - 20) / 5)) * 0.5);
////				r = 1; g = 0; b = 0;
//				break;
//			case 1:
//				spacing = screenSpacing; // 5..50
//				a = (float) (Math.min(1, Math.max(0, (spacing - 5) / 5)) * 0.5 +
//					Math.min(1, Math.max(0, (spacing - 40) / 10)) * 0.5);
////				r = 0; g = 1; b = 0;
//				break;
//			default:
//				spacing = screenSpacing * 5; // 20..250
////				a = Math.min(1, Math.max(0, (spacing - 100) / 50)) * 0.5f +
////					Math.min(1, Math.max(0, (spacing - 400) / 50)) * 0.5f;
//				a = 1;
////				r = 1; g = 1; b = 1;
//				break;
//			}
//			if (spacing < 5) {
//				continue;
//			}
//			
//			gl.glColor4f(r, g, b, a);
//			//gl.glColor4f(r1 * b + r0 * (1 - b), g1 * b + g0 * (1 - b), b1 * b + b0 * (1 - b), a);
//			
//			int xStart = (int) Math.round(-xCenter / spacing);
//			int xEnd = (int) Math.round((width - xCenter) / spacing);
//			int yStart = (int) Math.round(-yCenter / spacing);
//			int yEnd = (int) Math.round((height - yCenter) / spacing);
//			for (int x = xStart; x <= xEnd; x++) {
//				gl.glVertex2d(xCenter + x * spacing, 0);
//				gl.glVertex2d(xCenter + x * spacing, height);
//			}
//			for (int y = yStart; y <= yEnd; y++) {
//				gl.glVertex2d(0, height - yCenter - y * spacing);
//				gl.glVertex2d(width, height - yCenter - y * spacing);
//			}
//		}
//		gl.glEnd();
//		gl.glDisable(GL_BLEND);
//	}

	protected void drawOrigin() {
		GL gl = drawable.getGL();
		float radius = (float) transformUtil.computeNiceRadius(-modelView[11], component.getWidth(), component.getHeight()) / 2;
		Point3f p0 = new Point3f(0, 0, 0);
		Point3f px = new Point3f(radius, 0, 0);
		Point3f py = new Point3f(0, radius, 0);
		Point3f pz = new Point3f(0, 0, radius);
	
		
		
//		System.out.println("p0 = " + p0);
//		System.out.println("px = " + px);
//		System.out.println("py = " + py);
//		System.out.println("pz = " + pz);
		
		gl.glDisable(GL_LIGHTING);
		gl.glBegin(GL_LINES);
		gl.glColor3f(1, 0, 0);
		gl.glVertex3f(p0.x, p0.y, p0.z);
		gl.glVertex3f(px.x, px.y, px.z);
		gl.glColor3f(0, 1, 0);
		gl.glVertex3f(p0.x, p0.y, p0.z);
		gl.glVertex3f(py.x, py.y, py.z);
		gl.glColor3f(0, 0, 1);
		gl.glVertex3f(p0.x, p0.y, p0.z);
		gl.glVertex3f(pz.x, pz.y, pz.z);
		gl.glEnd();
		
//		gl.glDisable(GL_CULL_FACE);
//		for (int z = 0; z < 3; z++) {
//			Point3f a = new Point3f(-1, 1, z);
//			Point3f b = new Point3f( 1, 1, z);
//			Point3f c = new Point3f( 1,-1, z);
//			Point3f d = new Point3f(-1,-1, z);
//			transformUtil.world2Camera(a, a);
//			transformUtil.world2Camera(b, b);
//			transformUtil.world2Camera(c, c);
//			transformUtil.world2Camera(d, d);
//			if (z == 0) {
//				gl.glColor3f(1, 0, 0);
//			} else if (z == 1) {
//				gl.glColor3f(0, 1, 0);
//			} else if (z == 2) {
//				gl.glColor3f(0, 0, 1);
//			}
//			System.out.println(z + " " + a + " " + b + " " + c + " " + d);
//			gl.glBegin(GL_QUADS);
//			gl.glVertex3f(a.x, a.y, a.z);
//			gl.glVertex3f(b.x, b.y, b.z);
//			gl.glVertex3f(c.x, c.y, c.z);
//			gl.glVertex3f(d.x, d.y, d.z);
//			gl.glEnd();
//		}
		
		gl.glEnable(GL_LIGHTING);
	}
	
//	private void drawSelection(Selection selection) {
//		GL gl = drawable.getGL();
////		if (true) return;
//		selection.getNode().getLocal2WorldTransform(transformUtil, LOCAL);
//		transformUtil.getMatrix(TransformUtil.LOCAL, TransformUtil.CAMERA, modelView);
//		gl.glMatrixMode(GL_MODELVIEW);
//		gl.glLoadIdentity();
//		gl.glLoadMatrixd(modelView, 0);
//		
//		gl.glPointSize(4);
//		gl.glDisable(GL_LIGHTING);
//		Point3f p = new Point3f();
//		for (int pass = 0; pass < 2; pass++) {
//			if (pass == 0) {
//				gl.glDisable(GL_DEPTH_TEST);
//				gl.glEnable(GL_BLEND);
//				gl.glColor4f(1, 1, 0, 0.4f);
//			} else {
//				gl.glEnable(GL_DEPTH_TEST);
//				gl.glDisable(GL_BLEND);
//				gl.glColor3f(1, 1, 0);
//			}
//			gl.glBegin(GL_POINTS);
//			if (viewDef.getShowControlMeshAttribute().getBoolean()) {
//				for (AbstractVertex vertex : selection.getVertices()) {
//					vertex.getPosition(p);
//					gl.glVertex3f(p.x, p.y, p.z);
//				}
//			} else if (viewDef.getShowProjectedMeshAttribute().getBoolean()) {
//				for (AbstractVertex vertex : selection.getVertices()) {
//					vertex.getVertexPoint().getLimit(p);
//					gl.glVertex3f(p.x, p.y, p.z);
//				}
//			}
//			gl.glEnd();
//		}
//		
//		Point3f p0 = new Point3f();
//		Point3f p1 = new Point3f();
//		if (!getViewDef().getShowControlMeshAttribute().getBoolean() && selection.getVertices().size() > 1) {
//			for (int pass = 0; pass < 4; pass++) {
//				if (pass < 2) {
//					gl.glColor4f(1, 1, 0, 0.15f);
//					gl.glDisable(GL_DEPTH_TEST);
//				} else {
//					gl.glColor4f(1, 1, 0, 0.5f);
//					gl.glEnable(GL_DEPTH_TEST);
//				}
//				if (pass == 0 || pass == 2) {
//					gl.glBegin(GL_LINES);
//				} else {
//					gl.glBegin(GL_POINTS);
//				}
//				for (AbstractVertex v : selection.getVertices()) {
//					v.getPosition(p0);
//					gl.glVertex3f(p0.x, p0.y, p0.z);
//					if (pass == 0 || pass == 2) {
//						v.getVertexPoint().getLimit(p1);
//						gl.glVertex3f(p1.x, p1.y, p1.z);
//					}
//				}
//				gl.glEnd();
//			}
//		}
//		
//		gl.glPointSize(3);
//	}
	
	public void drawSelection(Selection selection, Color4f highlighColor) {
		GL gl = drawable.getGL();
//		selection.getNode().getLocal2WorldTransform(transformUtil, LOCAL);
//		transformUtil.getMatrix(TransformUtil.LOCAL, TransformUtil.CAMERA, modelView);
//		gl.glMatrixMode(GL_MODELVIEW);
//		gl.glLoadIdentity();
//		gl.glLoadMatrixd(modelView, 0);
		
		
		Point3f p = new Point3f();
		gl.glDepthMask(false);
		gl.glEnable(GL_BLEND);
		gl.glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA);
		switch (selection.getType()) {
		case VERTICES:
			gl.glPointSize(6);
			gl.glColor4f(highlighColor.x, highlighColor.y, highlighColor.z, highlighColor.w);
			gl.glBegin(GL_POINTS);
			for (AbstractVertex vertex : selection.getVertices()) {
				vertex.getPosition(p);
				gl.glVertex3f(p.x, p.y, p.z);
			}
			gl.glEnd();
			break;
		case EDGES:
			gl.glLineWidth(3);
			gl.glColor4f(highlighColor.x, highlighColor.y, highlighColor.z, highlighColor.w);
			gl.glBegin(GL_LINES);
			for (HalfEdge edge : selection.getEdges()) {
				edge.getVertex().getPosition(p);
				gl.glVertex3f(p.x, p.y, p.z);
				edge.getPairVertex().getPosition(p);
				gl.glVertex3f(p.x, p.y, p.z);
			}
			gl.glEnd();
			break;
		case FACES:
			gl.glLineWidth(2);
			for (Face face : selection.getFaces()) {
				gl.glInterleavedArrays(GL_N3F_V3F, 0, face.getControlSurface());
				gl.glColor4f(highlighColor.x, highlighColor.y, highlighColor.z, highlighColor.w * 0.5f);
				gl.glDrawArrays(GL_TRIANGLE_FAN, 0, face.getSides() + 2);
				gl.glColor4f(highlighColor.x, highlighColor.y, highlighColor.z, highlighColor.w);
				gl.glDrawArrays(GL_LINE_LOOP, 1, face.getSides());
			}
			break;
		}
		gl.glDisable(GL_BLEND);
		gl.glDepthMask(true);
	
//		gl.glPopMatrix();
	}
	
	public void drawSds2(Sds sds, boolean showControlMesh, boolean showLimit, boolean showProjectedMesh, int level, int editLevel, Color4f lineColor, GlMaterial meshMaterial) {		
		GL gl = drawable.getGL();
		Tuple3f p = new Point3f();
		
		/* draw limit surface */
		if (showLimit) {
			gl.glEnable(GL_LIGHTING);
			GlMaterial currentMaterial = null;
			for (Face face : sds.getFaces(level)) {
				GlMaterial faceMaterial = face.getMaterial().getGlMaterial();
				if (currentMaterial != faceMaterial) {
					setMaterial(GL_FRONT, faceMaterial.getArray());
					currentMaterial = faceMaterial;
				}
				gl.glInterleavedArrays(GL_N3F_V3F, 0, face.getLimitSurface());
				gl.glDrawArrays(GL_TRIANGLE_FAN, 0, face.getSides());
			}
		}
		
		/* draw control mesh */
		if (showControlMesh) {
			if (!showLimit) {
				// render solid control surface
				gl.glEnable(GL_LIGHTING);
				GlMaterial currentMaterial = null;
				for (Face face : sds.getFaces(editLevel)) {
					GlMaterial faceMaterial = face.getMaterial().getGlMaterial();
					if (currentMaterial != faceMaterial) {
						setMaterial(GL_FRONT, faceMaterial.getArray());
						currentMaterial = faceMaterial;
					}
//					face.getMidpointNormal(p);
//					gl.glNormal3d(p.x, p.y, p.z);
					gl.glInterleavedArrays(GL_N3F_V3F, 0, face.getControlSurface());
					gl.glDrawArrays(GL_TRIANGLE_FAN, 0, face.getSides() + 2);
				}
			} 
			// render wireframe
			gl.glDisable(GL_LIGHTING);
			gl.glColor4f(lineColor.x, lineColor.y, lineColor.z, lineColor.w);
			gl.glBegin(GL_LINES);
			for (HalfEdge edge : sds.getEdges(editLevel, false)) {
				if (edge.isPrimary() || edge.getPairFace() == null) {
					edge.getVertex().getPosition(p);
					gl.glVertex3f(p.x, p.y, p.z);
					edge.getPairVertex().getPosition(p);
					gl.glVertex3f(p.x, p.y, p.z);
				}
			}
			gl.glEnd();
			
		}
		
		/* draw projected mesh */
		if (showProjectedMesh) {
			gl.glEnable(GL_LIGHTING);
			setMaterial(GL_FRONT, meshMaterial.getArray());
			gl.glBegin(GL_LINES);
			int levelsToGo = level - editLevel;
			HalfEdge[] subEdges = new HalfEdge[2];
			for (HalfEdge edge : sds.getEdges(editLevel, false)) {
				if (edge.isPrimary() || edge.getPairFace() == null) {
					drawEdgeLimit(p, levelsToGo, edge, subEdges);
				}
			}
			gl.glEnd();
		}
		
		/* draw stray edges/vertices */
		gl.glDisable(GL_LIGHTING);
		gl.glColor3f(0.5f, 0.5f, 1.0f);
		gl.glBegin(GL_LINES);
		for (HalfEdge strayEdge : sds.getStrayEdges()) {
			strayEdge.getVertex().getPosition(p);
			gl.glVertex3f(p.x, p.y, p.z);
			strayEdge.getPairVertex().getPosition(p);
			gl.glVertex3f(p.x, p.y, p.z);
		}
		gl.glEnd();
		gl.glBegin(GL_POINTS);
		for (BaseVertex strayVertex : sds.getStrayVertices()) {
			strayVertex.getPosition(p);
			gl.glVertex3f(p.x, p.y, p.z);
		}
		gl.glEnd();
	}
	
	private void drawEdgeLimit(Tuple3f p, int levelsToGo, HalfEdge edge, HalfEdge[] subEdges) {
		GL gl = drawable.getGL();
		if (levelsToGo > 0) {
			Face face = edge.getFace();
			face.getSubEdges(edge.getFaceEdgeIndex(), subEdges);
			HalfEdge edge0 = subEdges[0];
			HalfEdge edge1 = subEdges[1];
			drawEdgeLimit(p, levelsToGo - 1, edge0, subEdges);
			drawEdgeLimit(p, levelsToGo - 1, edge1, subEdges);
		} else {
			edge.getVertex().getNormal(p);
			gl.glNormal3d(p.x, p.y, p.z);
			edge.getVertex().getLimit(p);
			gl.glVertex3d(p.x, p.y, p.z);
			edge.getPairVertex().getNormal(p);
			gl.glNormal3d(p.x, p.y, p.z);
			edge.getPairVertex().getLimit(p);
			gl.glVertex3d(p.x, p.y, p.z);
		}
	}
	
	
	

	protected void drawInfo() {
		rasterMode();
//		gl.glColor3f(COLORS.text.x, COLORS.text.y, COLORS.text.z);
		String fps = Long.toString(1000000000 / (System.nanoTime() - time));
		drawString(getInfo(), 4, 16);
		
		drawString("repaint " + (repaintCount++) + " " + fps + "fps", 4, 32);
	}
	
	public void drawString(String string, int x, int y) {
		GL gl = drawable.getGL();
		gl.glEnable(GL_BLEND);
		gl.glColor4f(0, 0, 0, 0.5f);
		for (int yy = y - 1; yy < y + 2; yy++) {
			for (int xx = x - 1; xx < x + 2; xx++) {
				gl.glRasterPos2i(xx, yy);							// set raster position
				char[] c = string.toCharArray();
			    for (int i = 0, n = c.length; i < n; i++) {		// loop over characters
			    	if (c[i] < 256) {
			    		gl.glCallList(fontOffset + c[i]);		// call display list that draws a character
			    	}
			    }
			}
		}
		gl.glColor4f(1, 1, 1, 0.75f);
		gl.glRasterPos2i(x, y);							// set raster position
		char[] c = string.toCharArray();
	    for (int i = 0, n = c.length; i < n; i++) {		// loop over characters
	    	if (c[i] < 256) {
	    		gl.glCallList(fontOffset + c[i]);		// call display list that draws a character
	    	}
	    }
	    gl.glDisable(GL_BLEND);
	}
	
	public void spatialMode() {
		GL gl = drawable.getGL();
		float w = (float) component.getWidth() / 2;
		float h = (float) component.getHeight() / 2;
		gl.glMatrixMode(GL_PROJECTION);
		gl.glLoadIdentity();
		if (viewDef instanceof PerspectiveViewDef) {
			PerspectiveViewDef perspectiveView = ((PerspectiveViewDef) viewDef);
//			float a = (float) (17.5 / perspective.getFocalLength());
			float a = 0.5f / (float) perspectiveView.getRelativeFocalLength();
			float b = a * h / w;
//			float a = 17.5f / (float) camera.focalLength.get(); 	// 35/focallength/2
//			float b = a * h / w;
			gl.glFrustum(-a, a, -b, b, nearClip, farClip);
		} else {
			gl.glOrtho(-w, w, -h, h, -farClip, farClip);
		}
		gl.glDepthFunc(GL_LESS);
		gl.glMatrixMode(GL_MODELVIEW);
		gl.glLoadIdentity();
//		gl.glScalef(1, 1, -1); // switch to left handed coordinate system
		gl.glEnable(GL_DEPTH_TEST);
		gl.glShadeModel(GL_SMOOTH);
	}
	
	public void rasterMode() {
		GL gl = drawable.getGL();
		int w = drawable.getWidth();
		int h = drawable.getHeight();
		gl.glViewport(0, 0, w, h);
	    gl.glMatrixMode(GL_PROJECTION);
	    gl.glLoadIdentity();
	    gl.glOrtho(0, w, h, 0, 1, -1);
	    gl.glMatrixMode(GL_MODELVIEW);
	    gl.glLoadIdentity();
	    gl.glDisable(GL_LIGHTING);
		gl.glDisable(GL_DEPTH_TEST);
		gl.glShadeModel(GL_FLAT);
	}
	
	public void validateScreenShotTexture() {
		validateScreenShotTexture(true);
	}
		
	public void validateScreenShotTexture(boolean front) {
		if (screenshotTextureValid) {
			return;
		}
		GL gl = drawable.getGL();
		rasterMode();
		gl.glEnable(GL_TEXTURE_2D);
		gl.glBindTexture(GL.GL_TEXTURE_2D, screenshotTexture);
		gl.glTexParameteri(GL.GL_TEXTURE_2D, GL.GL_TEXTURE_MIN_FILTER, GL.GL_NEAREST);
        gl.glTexParameteri(GL.GL_TEXTURE_2D, GL.GL_TEXTURE_MAG_FILTER, GL.GL_NEAREST);
        
		int txWidth = textureSize(component.getWidth());
		int txHeight = textureSize(component.getHeight());
		
		gl.glReadBuffer(front ? GL_FRONT : GL_BACK);
		gl.glCopyTexImage2D(GL_TEXTURE_2D, 0, GL_RGB, 0, 0, txWidth, txHeight, 0);
		
		screenShotTxCoords[0] = 0.0f;	// top
		screenShotTxCoords[1] = 0.0f;										// left
		screenShotTxCoords[2] = (float) component.getHeight() / txHeight;										// bottom
		screenShotTxCoords[3] = (float) component.getWidth() / txWidth;				// right
		
//		gl.glReadPixels(0, 0, component.getWidth(), component.getHeight(), GL_DEPTH_COMPONENT, GL_FLOAT, depthBuffer);
//		return Viewport.farClip - 2 * Viewport.farClip * buffer.get(0) - 1;
		
		screenshotTextureValid = true;
		gl.glDisable(GL_TEXTURE_2D);
		spatialMode();
//		System.out.println("texture Updated");
	}
	
	public void validateDepthBuffer() {
		validateDepthBuffer(true);
	}
		
	public void validateDepthBuffer(boolean front) {
		if (depthBufferValid) {
			return;
		}
		GL gl = drawable.getGL();
		gl.glReadBuffer(front ? GL_FRONT : GL_BACK);
		gl.glReadPixels(0, 0, component.getWidth(), component.getHeight(), GL_DEPTH_COMPONENT, GL_FLOAT, depthBuffer);
		depthBufferValid = true;
	}
	
	public float getDepthAt(int x, int y) {
		validateDepthBuffer();
		int h = component.getHeight();
		int w = component.getWidth();
		if (x < 0 || x >= w || y < 0 || y >= h) {
			return -farClip;
		}
		int index = x + (h - y - 1) * w - 1;
		index = y * w + x;
		index = (h - y - 1) * w + x;
//		System.out.println("x=" + x + " y=" + y + " w=" + w + " h=" + h + " i=" + index + " capacity=" + depthBuffer.capacity());
		buffer.rewind();
		float depth = farClip - 2 * Viewport.farClip * depthBuffer.get(index) - 1;
//		System.out.println("x= " + x + " y=" + y + " depth=" + depth);
		return depth;
	}
	
	public void drawScreenShot(int x0, int y0, int x1, int y1, float alpha) {
		GL gl = drawable.getGL();
//		System.out.println("drawScreenshot");
//		gl.glTexParameteri(GL.GL_TEXTURE_2D, GL.GL_TEXTURE_MIN_FILTER, GL.GL_NEAREST);
//        gl.glTexParameteri(GL.GL_TEXTURE_2D, GL.GL_TEXTURE_MAG_FILTER, GL.GL_NEAREST);
//       
//       
//        gl.glMatrixMode(GL_TEXTURE);
//        gl.glLoadIdentity();
		rasterMode();
        gl.glEnable(GL_TEXTURE_2D);
//        gl.glDisable(GL_TEXTURE_GEN_Q);
//        gl.glDisable(GL_TEXTURE_GEN_R);
//        gl.glDisable(GL_TEXTURE_GEN_S);
//        gl.glDisable(GL_TEXTURE_GEN_T);
		gl.glBindTexture(GL_TEXTURE_2D, screenshotTexture);
		
		
//		Random rnd = new Random();
//		float top = rnd.nextFloat() % 1;
//		float bottom = rnd.nextFloat() % 1;
//		float left = rnd.nextFloat() % 1;
//		float right = rnd.nextFloat() % 1;
		
		float w = component.getWidth();
		float h = component.getHeight();
		
		float tx_h = screenShotTxCoords[2];
		float tx_w = screenShotTxCoords[3];
		
		float top = tx_h - y0 * tx_h / h;
		float left = x0 * tx_w / w;
		float bottom = tx_h - y1 * tx_h / h;
		float right = x1 * tx_w / w;
		
		gl.glColor3f(alpha, alpha, alpha);
		gl.glBegin(GL_QUADS);
//		gl.glTexCoord2f(screenShotTxCoords[1], screenShotTxCoords[0]);
		gl.glTexCoord2f(left, top);
		gl.glVertex2f(x0, y0);
//		gl.glTexCoord2f(screenShotTxCoords[1], screenShotTxCoords[2]);
		gl.glTexCoord2f(left, bottom);
		gl.glVertex2f(x0, y1);
//		gl.glTexCoord2f(screenShotTxCoords[3], screenShotTxCoords[2]);
		gl.glTexCoord2f(right, bottom);
		gl.glVertex2f(x1, y1);
//		gl.glTexCoord2f(screenShotTxCoords[3], screenShotTxCoords[0]);
		gl.glTexCoord2f(right, top);
		gl.glVertex2f(x1, y0);
		gl.glEnd();
		gl.glDisable(GL_TEXTURE_2D);
		
//		System.out.println("top = " + screenShotTxCoords[0]);
//		System.out.println("left = " + screenShotTxCoords[1]);
//		System.out.println("bottom = " + screenShotTxCoords[2]);
//		System.out.println("right = " + screenShotTxCoords[3]);
	}
	
//	public void redrawBackground() {
//		GLContext glContext = ((GLAutoDrawable) component).getContext();
//		if (glContext.makeCurrent() == GLContext.CONTEXT_CURRENT) {
//			GL gl = glContext.getGL();
//			gl.glDrawBuffer(GL_FRONT);
//			gl.glDisable(GL_LIGHTING);
//			gl.glDepthMask(false);
//			gl.glDisable(GL_DEPTH_TEST);
////			gl.glEnable(GL_BLEND);
////			gl.glBlendFunc(GL_ONE_MINUS_DST_ALPHA, GL_DST_ALPHA);
//			rasterMode();
//			float h = component.getHeight();
//			float w = component.getWidth();
//			float z = +0.9f;
//			Color3f background = active ? COLORS.activeBackground : COLORS.background;
//			gl.glColor3f(background.x, background.y, background.z);	// set background color
//			gl.glBegin(GL_QUADS);
//			System.out.println("redraw background " + active);
//			gl.glVertex3f(0, 0, z);
//			gl.glVertex3f(0, h, z);
//			gl.glVertex3f(w, h, z);
//			gl.glVertex3f(w, 0, z);
//			gl.glEnd();
//			gl.glDepthMask(true);
//			gl.glDrawBuffer(GL_BACK);
//			gl.glFlush();
//			glContext.release();
//		}
//	}
	
	public void disposeScreenShotTexture() {
		GL gl = drawable.getGL();
		gl.glDeleteTextures(0, new int[] { screenshotTexture }, 0);
	}
	
	private int textureSize(int size) {
		if (size > maxTextureSize) {
			return maxTextureSize;
		}
		for (int i = 6; i < 24; i++) {
			int s = 1 << i;
			if (s >= size) {
				return s;
			}
		}
		assert false : "should never get here";
		return -1;
	}
	
	private void loadShader(InputStream in, GL gl, int shader) throws IOException {
		BufferedReader reader = new BufferedReader(new InputStreamReader(in));
		String line;
		List<String> list = new ArrayList<String>(128);
		while ((line = reader.readLine()) != null) {
			list.add(line + "\n");
		}
		String[] source = list.toArray(new String[list.size()]);
		int[] length = new int[source.length];
		for (int i = 0; i < length.length; i++) {
			length[i] = source[i].length();
		}
		gl.glShaderSource(shader, source.length, source, length, 0);
		in.close();
	}
	
	private void printShaderInfo(GL gl, int shader) {
		int[] info = new int[5];
		gl.glGetShaderiv(shader, GL_SHADER_TYPE, info, 0);
		gl.glGetShaderiv(shader, GL_DELETE_STATUS, info, 1);
		gl.glGetShaderiv(shader, GL_COMPILE_STATUS, info, 2);
		gl.glGetShaderiv(shader, GL_INFO_LOG_LENGTH, info, 3);
		gl.glGetShaderiv(shader, GL_SHADER_SOURCE_LENGTH, info, 4);
		System.out.println("Shader Info for shader " + shader);
		System.out.println("=========================");
		System.out.println("GL_SHADER_TYPE = " + (info[0] == GL_VERTEX_SHADER ? "GL_VERTEX_SHADER" : info[0] == GL_FRAGMENT_SHADER ? "GL_FRAGMENT_SHADER" : "unknown"));
		System.out.println("GL_DELETE_STATUS = " + (info[1] == GL_TRUE ? "true" : "false"));
		System.out.println("GL_COMPILE_STATUS = " + (info[2] == GL_TRUE ? "true" : "false"));
		System.out.println("GL_INFO_LOG_LENGTH = " + info[3]);
		System.out.println("GL_SHADER_SOURCE_LENGTH = " + info[4]);
		System.out.println();
		int infoLogLength = info[3];
		if (infoLogLength > 0) {
			int[] length = new int[1];
			byte[] infoLog = new byte[infoLogLength];
			gl.glGetShaderInfoLog(shader, infoLogLength, length, 0, infoLog, 0);
			System.out.println(new String(infoLog));
		}
	}
	
	private void printProgramInfo(GL gl, int program) {
		int[] info = new int[9];
		gl.glGetProgramiv(program, GL_DELETE_STATUS, info, 0);
		gl.glGetProgramiv(program, GL_LINK_STATUS, info, 1);
		gl.glGetProgramiv(program, GL_VALIDATE_STATUS, info, 2);
		gl.glGetProgramiv(program, GL_INFO_LOG_LENGTH, info, 3);
		gl.glGetProgramiv(program, GL_ATTACHED_SHADERS, info, 4);
		gl.glGetProgramiv(program, GL_ACTIVE_ATTRIBUTES, info, 5);
		gl.glGetProgramiv(program, GL_ACTIVE_ATTRIBUTE_MAX_LENGTH, info, 6);
		gl.glGetProgramiv(program, GL_ACTIVE_UNIFORMS, info, 7);
		gl.glGetProgramiv(program, GL_ACTIVE_UNIFORM_MAX_LENGTH, info, 8);	
		
		System.out.println("Program Info for program " + program);
		System.out.println("=========================");
		System.out.println("GL_DELETE_STATUS = " + (info[0] == GL_TRUE ? "true" : "false"));
		System.out.println("GL_LINK_STATUS = " + (info[1] == GL_TRUE ? "true" : "false"));
		System.out.println("GL_VALIDATE_STATUS = " + (info[2] == GL_TRUE ? "true" : "false"));
		System.out.println("GL_INFO_LOG_LENGTH = " + info[3]);
		System.out.println("GL_ATTACHED_SHADERS = " + info[4]);
		System.out.println("GL_ACTIVE_ATTRIBUTES = " + info[5]);
		System.out.println("GL_ACTIVE_ATTRIBUTE_MAX_LENGTH = " + info[6]);
		System.out.println("GL_ACTIVE_UNIFORMS = " + info[7]);
		System.out.println("GL_ACTIVE_UNIFORM_MAX_LENGTH = " + info[8]);
		System.out.println();
		int infoLogLength = info[3];
		if (infoLogLength > 0) {
			int[] length = new int[1];
			byte[] infoLog = new byte[infoLogLength];
			gl.glGetProgramInfoLog(program, infoLogLength, length, 0, infoLog, 0);
			System.out.println(new String(infoLog));
		}
	}
}
