package com.jpatch.boundary;

import com.jpatch.settings.*;
import com.jpatch.afw.attributes.CollectionAttr;
import com.jpatch.afw.vecmath.Transform;
import com.jpatch.afw.vecmath.TransformUtil;
import com.jpatch.afw.vecmath.Utils3d;
import static com.jpatch.afw.vecmath.TransformUtil.*;
import com.jpatch.boundary.tools.*;
import com.jpatch.entity.*;
import com.jpatch.entity.sds2.*;
import com.sun.opengl.util.*;
//import com.sun.opengl.util.*;

import java.awt.Component;
import java.awt.event.MouseWheelEvent;
import java.awt.event.MouseWheelListener;
import java.io.*;
import java.nio.FloatBuffer;
import java.util.*;

import javax.media.opengl.*;
import static javax.media.opengl.GL.*;

import javax.vecmath.*;


public class ViewportGl extends Viewport {
	private static Matrix4d IDENTITY = Utils3d.createIdentityMatrix4d();
	private int repaintCount = 0;
	
	private static final boolean LIGHTWEIGHT = false;
//	private static final double CLEAR_DEPTH = 100000;
	private static final ColorSettings COLORS = Settings.getInstance().colors;
	private static final RealtimeRendererSettings RENDERER = Settings.getInstance().realtimeRenderer;
	
	final GLAutoDrawable drawable;
	private GL gl;
	private final Point3f p = new Point3f();
	private final Vector3f v = new Vector3f();
	
//	private final FragmentTesselator kernel = new FragmentTesselator();
//	private static final Dicer dicer = new Dicer();
	private int subdivLevel = 4;
	
	private long time;
	
	private int program;
	private boolean useProgram;
	private boolean canUseProgram;
	private int num;
	
	private double[] modelView = new double[16];
	
//	private Matrix4f modelView = new Matrix4f();
	private TransformUtil transformUtil = new TransformUtil();
//	private final TransformUtil transformUtil = new TransformUtil();
	
	/**
	 * The unicode characters 0 to 255 as 16x14 bitmaps (autogenerated from
	 * default "Sans Serif" 14 font).
	 */
	private static final byte[][] fontRaster = new byte[][] {
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,64,0,0,0,64,0,64,0,64,0,64,0,64,0,64,0,64,0,0,0,0,0,0,0},
		{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-96,0,-96,0,-96,0,0,0,0,0,0,0},
		{0,0,0,0,72,0,72,0,36,0,-2,0,36,0,127,0,36,0,18,0,18,0,0,0,0,0,0,0},
		{0,0,16,0,56,0,84,0,20,0,20,0,56,0,80,0,80,0,84,0,56,0,16,0,0,0,0,0},
		{0,0,0,0,-122,0,73,0,41,0,22,0,16,0,104,0,-108,0,-110,0,97,0,0,0,0,0,0,0},
		{0,0,0,0,62,0,68,0,74,0,74,0,50,0,40,0,36,0,36,0,24,0,0,0,0,0,0,0},
		{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,64,0,64,0,64,0,0,0,0,0,0,0},
		{16,0,32,0,32,0,64,0,64,0,64,0,64,0,64,0,32,0,32,0,16,0,0,0,0,0,0,0},
		{-128,0,64,0,64,0,32,0,32,0,32,0,32,0,32,0,64,0,64,0,-128,0,0,0,0,0,0,0},
		{0,0,0,0,0,0,0,0,0,0,0,0,0,0,80,0,80,0,-8,0,32,0,0,0,0,0,0,0},
		{0,0,0,0,8,0,8,0,8,0,127,0,8,0,8,0,8,0,0,0,0,0,0,0,0,0,0,0},
		{-128,0,64,0,64,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,0,0,0,0,0,0,124,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,64,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
		{64,0,64,0,32,0,32,0,32,0,16,0,16,0,16,0,16,0,8,0,8,0,0,0,0,0,0,0},
		{0,0,0,0,24,0,36,0,66,0,66,0,66,0,66,0,66,0,36,0,24,0,0,0,0,0,0,0},
		{0,0,0,0,62,0,8,0,8,0,8,0,8,0,8,0,8,0,40,0,24,0,0,0,0,0,0,0},
		{0,0,0,0,124,0,64,0,32,0,16,0,8,0,4,0,4,0,4,0,120,0,0,0,0,0,0,0},
		{0,0,64,0,56,0,4,0,4,0,8,0,48,0,8,0,4,0,4,0,120,0,0,0,0,0,0,0},
		{0,0,0,0,4,0,4,0,4,0,126,0,68,0,36,0,20,0,12,0,4,0,0,0,0,0,0,0},
		{0,0,0,0,112,0,8,0,4,0,4,0,8,0,112,0,64,0,64,0,124,0,0,0,0,0,0,0},
		{0,0,0,0,24,0,36,0,66,0,66,0,100,0,88,0,64,0,32,0,30,0,0,0,0,0,0,0},
		{0,0,0,0,32,0,32,0,16,0,16,0,8,0,8,0,4,0,2,0,126,0,0,0,0,0,0,0},
		{0,0,0,0,60,0,66,0,66,0,66,0,60,0,36,0,66,0,66,0,60,0,0,0,0,0,0,0},
		{0,0,0,0,120,0,4,0,2,0,26,0,38,0,66,0,66,0,36,0,24,0,0,0,0,0,0,0},
		{0,0,0,0,64,0,0,0,0,0,0,0,0,0,0,0,64,0,0,0,0,0,0,0,0,0,0,0},
		{-128,0,64,0,64,0,0,0,0,0,0,0,0,0,0,0,64,0,0,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,1,0,6,0,8,0,48,0,8,0,6,0,1,0,0,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,0,0,0,0,63,0,0,0,63,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,32,0,24,0,4,0,3,0,4,0,24,0,32,0,0,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,64,0,0,0,64,0,64,0,32,0,16,0,8,0,8,0,-16,0,0,0,0,0,0,0},
		{0,0,0,0,30,0,32,0,75,0,86,-128,82,64,73,64,39,64,16,-128,15,0,0,0,0,0,0,0},
		{0,0,0,0,-128,-128,65,0,127,0,34,0,34,0,20,0,20,0,8,0,8,0,0,0,0,0,0,0},
		{0,0,0,0,120,0,68,0,68,0,68,0,120,0,68,0,68,0,68,0,120,0,0,0,0,0,0,0},
		{0,0,0,0,30,0,32,0,64,0,64,0,64,0,64,0,64,0,32,0,30,0,0,0,0,0,0,0},
		{0,0,0,0,124,0,66,0,65,0,65,0,65,0,65,0,65,0,66,0,124,0,0,0,0,0,0,0},
		{0,0,0,0,126,0,64,0,64,0,64,0,124,0,64,0,64,0,64,0,126,0,0,0,0,0,0,0},
		{0,0,0,0,64,0,64,0,64,0,64,0,120,0,64,0,64,0,64,0,120,0,0,0,0,0,0,0},
		{0,0,0,0,31,0,33,0,65,0,65,0,64,0,64,0,64,0,32,0,31,0,0,0,0,0,0,0},
		{0,0,0,0,65,0,65,0,65,0,65,0,127,0,65,0,65,0,65,0,65,0,0,0,0,0,0,0},
		{0,0,0,0,64,0,64,0,64,0,64,0,64,0,64,0,64,0,64,0,64,0,0,0,0,0,0,0},
		{-64,0,32,0,32,0,32,0,32,0,32,0,32,0,32,0,32,0,32,0,32,0,0,0,0,0,0,0},
		{0,0,0,0,65,0,66,0,68,0,72,0,80,0,112,0,72,0,68,0,66,0,0,0,0,0,0,0},
		{0,0,0,0,124,0,64,0,64,0,64,0,64,0,64,0,64,0,64,0,64,0,0,0,0,0,0,0},
		{0,0,0,0,65,0,73,0,73,0,85,0,85,0,85,0,99,0,99,0,65,0,0,0,0,0,0,0},
		{0,0,0,0,65,0,67,0,69,0,69,0,73,0,81,0,81,0,97,0,65,0,0,0,0,0,0,0},
		{0,0,0,0,28,0,34,0,65,0,65,0,65,0,65,0,65,0,34,0,28,0,0,0,0,0,0,0},
		{0,0,0,0,64,0,64,0,64,0,64,0,120,0,68,0,68,0,68,0,120,0,0,0,0,0,0,0},
		{1,-128,2,0,28,0,34,0,65,0,65,0,65,0,65,0,65,0,34,0,28,0,0,0,0,0,0,0},
		{0,0,0,0,65,0,66,0,68,0,72,0,120,0,68,0,66,0,66,0,124,0,0,0,0,0,0,0},
		{0,0,0,0,-16,0,8,0,8,0,8,0,48,0,64,0,-128,0,-128,0,124,0,0,0,0,0,0,0},
		{0,0,0,0,16,0,16,0,16,0,16,0,16,0,16,0,16,0,16,0,-2,0,0,0,0,0,0,0},
		{0,0,0,0,60,0,66,0,66,0,66,0,66,0,66,0,66,0,66,0,66,0,0,0,0,0,0,0},
		{0,0,0,0,16,0,16,0,40,0,40,0,40,0,68,0,68,0,-126,0,-126,0,0,0,0,0,0,0},
		{0,0,0,0,17,0,17,0,42,-128,42,-128,42,-128,42,-128,42,-128,68,64,68,64,0,0,0,0,0,0},
		{0,0,0,0,-126,0,68,0,40,0,40,0,16,0,40,0,40,0,68,0,-126,0,0,0,0,0,0,0},
		{0,0,0,0,16,0,16,0,16,0,16,0,16,0,40,0,40,0,68,0,-126,0,0,0,0,0,0,0},
		{0,0,0,0,124,0,64,0,32,0,32,0,16,0,8,0,8,0,4,0,124,0,0,0,0,0,0,0},
		{96,0,64,0,64,0,64,0,64,0,64,0,64,0,64,0,64,0,64,0,96,0,0,0,0,0,0,0},
		{8,0,8,0,16,0,16,0,16,0,32,0,32,0,32,0,32,0,64,0,64,0,0,0,0,0,0,0},
		{96,0,32,0,32,0,32,0,32,0,32,0,32,0,32,0,32,0,32,0,96,0,0,0,0,0,0,0},
		{0,0,0,0,0,0,0,0,0,0,-126,0,68,0,68,0,40,0,16,0,16,0,0,0,0,0,0,0},
		{0,0,120,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,8,0,16,0,0,0,0,0},
		{0,0,0,0,62,0,68,0,68,0,60,0,4,0,68,0,56,0,0,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,92,0,98,0,66,0,66,0,66,0,98,0,92,0,64,0,64,0,0,0,0,0,0,0},
		{0,0,0,0,56,0,64,0,64,0,64,0,64,0,64,0,56,0,0,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,58,0,70,0,66,0,66,0,66,0,70,0,58,0,2,0,2,0,0,0,0,0,0,0},
		{0,0,0,0,60,0,64,0,64,0,124,0,68,0,68,0,56,0,0,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,64,0,64,0,64,0,64,0,64,0,64,0,-32,0,64,0,48,0,0,0,0,0,0,0},
		{120,0,4,0,52,0,76,0,68,0,68,0,68,0,68,0,60,0,0,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,68,0,68,0,68,0,68,0,68,0,100,0,88,0,64,0,64,0,0,0,0,0,0,0},
		{0,0,0,0,64,0,64,0,64,0,64,0,64,0,64,0,64,0,0,0,64,0,0,0,0,0,0,0},
		{-64,0,32,0,32,0,32,0,32,0,32,0,32,0,32,0,32,0,0,0,32,0,0,0,0,0,0,0},
		{0,0,0,0,66,0,68,0,72,0,112,0,80,0,72,0,68,0,64,0,64,0,0,0,0,0,0,0},
		{0,0,0,0,64,0,64,0,64,0,64,0,64,0,64,0,64,0,64,0,64,0,0,0,0,0,0,0},
		{0,0,0,0,68,64,68,64,68,64,68,64,68,64,102,64,89,-128,0,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,68,0,68,0,68,0,68,0,68,0,100,0,88,0,0,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,56,0,68,0,68,0,68,0,68,0,68,0,56,0,0,0,0,0,0,0,0,0,0,0},
		{64,0,64,0,92,0,98,0,66,0,66,0,66,0,98,0,92,0,0,0,0,0,0,0,0,0,0,0},
		{2,0,2,0,58,0,70,0,66,0,66,0,66,0,70,0,58,0,0,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,64,0,64,0,64,0,64,0,64,0,96,0,88,0,0,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,112,0,8,0,8,0,48,0,64,0,64,0,56,0,0,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,32,0,64,0,64,0,64,0,64,0,64,0,-32,0,64,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,52,0,76,0,68,0,68,0,68,0,68,0,68,0,0,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,16,0,40,0,40,0,40,0,68,0,68,0,-126,0,0,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,34,0,34,0,85,0,85,0,85,0,-120,-128,-120,-128,0,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,68,0,40,0,40,0,16,0,40,0,40,0,68,0,0,0,0,0,0,0,0,0,0,0},
		{32,0,16,0,16,0,40,0,40,0,68,0,68,0,-126,0,-126,0,0,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,124,0,64,0,32,0,16,0,8,0,4,0,124,0,0,0,0,0,0,0,0,0,0,0},
		{32,0,64,0,64,0,64,0,64,0,-128,0,64,0,64,0,64,0,64,0,32,0,0,0,0,0,0,0},
		{64,0,64,0,64,0,64,0,64,0,64,0,64,0,64,0,64,0,64,0,64,0,0,0,0,0,0,0},
		{64,0,32,0,32,0,32,0,32,0,16,0,32,0,32,0,32,0,32,0,64,0,0,0,0,0,0,0},
		{0,0,0,0,0,0,0,0,0,0,76,0,50,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,127,0,65,0,65,0,65,0,65,0,65,0,65,0,127,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
		{64,0,64,0,64,0,64,0,64,0,64,0,64,0,0,0,64,0,0,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,16,0,60,0,112,0,80,0,80,0,80,0,80,0,60,0,16,0,0,0,0,0,0,0},
		{0,0,0,0,126,0,32,0,32,0,32,0,120,0,32,0,32,0,32,0,30,0,0,0,0,0,0,0},
		{0,0,0,0,0,0,-126,0,124,0,68,0,68,0,68,0,124,0,-126,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,16,0,16,0,124,0,16,0,124,0,16,0,40,0,68,0,-126,0,0,0,0,0,0,0},
		{64,0,64,0,64,0,64,0,0,0,0,0,0,0,64,0,64,0,64,0,64,0,0,0,0,0,0,0},
		{124,0,2,0,2,0,28,0,34,0,66,0,68,0,56,0,64,0,64,0,62,0,0,0,0,0,0,0},
		{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,40,0,0,0,0,0,0,0},
		{0,0,0,0,62,0,65,0,-100,-128,-96,-128,-96,-128,-96,-128,-100,-128,65,0,62,0,0,0,0,0,0,0},
		{0,0,0,0,0,0,0,0,0,0,0,0,0,0,120,0,112,0,16,0,96,0,0,0,0,0,0,0},
		{0,0,0,0,0,0,20,0,40,0,80,0,40,0,20,0,0,0,0,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,0,0,0,0,1,0,1,0,63,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,0,0,0,0,0,0,124,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,0,0,0,0,0,0,0,0,56,0,84,0,84,0,68,0,56,0,0,0,0,0,0,0},
		{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-8,0,0,0,0,0},
		{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,112,0,80,0,112,0,0,0,0,0,0,0},
		{0,0,0,0,62,0,0,0,8,0,8,0,62,0,8,0,8,0,0,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,0,0,0,0,0,0,112,0,64,0,32,0,16,0,16,0,96,0,0,0,0,0,0,0},
		{0,0,0,0,0,0,0,0,0,0,96,0,16,0,16,0,96,0,16,0,96,0,0,0,0,0,0,0},
		{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,32,0,16,0,0,0,0,0},
		{64,0,64,0,116,0,76,0,68,0,68,0,68,0,68,0,68,0,0,0,0,0,0,0,0,0,0,0},
		{10,0,10,0,10,0,10,0,10,0,10,0,10,0,26,0,58,0,58,0,30,0,0,0,0,0,0,0},
		{0,0,0,0,0,0,0,0,0,0,64,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
		{8,0,16,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,0,0,0,0,0,0,112,0,32,0,32,0,32,0,96,0,32,0,0,0,0,0,0,0},
		{0,0,0,0,0,0,0,0,0,0,0,0,0,0,48,0,72,0,72,0,48,0,0,0,0,0,0,0},
		{0,0,0,0,0,0,-96,0,80,0,40,0,80,0,-96,0,0,0,0,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,64,-128,35,-64,18,-128,49,-128,41,-128,36,-128,36,0,98,0,33,0,0,0,0,0,0,0},
		{0,0,0,0,67,-128,34,0,17,0,48,-128,40,-128,39,0,36,0,98,0,33,0,0,0,0,0,0,0},
		{0,0,0,0,32,-128,19,-64,10,-128,105,-128,21,-128,18,-128,98,0,17,0,96,-128,0,0,0,0,0,0},
		{120,0,-128,0,-128,0,64,0,32,0,16,0,16,0,0,0,16,0,0,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,-128,-128,65,0,127,0,34,0,34,0,20,0,20,0,8,0,8,0,0,0,4,0,8,0},
		{0,0,0,0,-128,-128,65,0,127,0,34,0,34,0,20,0,20,0,8,0,8,0,0,0,8,0,4,0},
		{0,0,0,0,-128,-128,65,0,127,0,34,0,34,0,20,0,20,0,8,0,8,0,0,0,20,0,8,0},
		{0,0,0,0,-128,-128,65,0,127,0,34,0,34,0,20,0,20,0,8,0,8,0,0,0,44,0,52,0},
		{0,0,0,0,-128,-128,65,0,127,0,34,0,34,0,20,0,20,0,8,0,8,0,0,0,20,0,0,0},
		{0,0,0,0,-128,-128,65,0,127,0,34,0,34,0,20,0,20,0,8,0,8,0,28,0,20,0,28,0},
		{0,0,0,0,-125,-32,66,0,62,0,34,0,19,-64,10,0,10,0,6,0,3,-32,0,0,0,0,0,0},
		{4,0,8,0,30,0,32,0,64,0,64,0,64,0,64,0,64,0,32,0,30,0,0,0,0,0,0,0},
		{0,0,0,0,126,0,64,0,64,0,64,0,124,0,64,0,64,0,64,0,126,0,0,0,8,0,16,0},
		{0,0,0,0,126,0,64,0,64,0,64,0,124,0,64,0,64,0,64,0,126,0,0,0,16,0,8,0},
		{0,0,0,0,126,0,64,0,64,0,64,0,124,0,64,0,64,0,64,0,126,0,0,0,20,0,8,0},
		{0,0,0,0,126,0,64,0,64,0,64,0,124,0,64,0,64,0,64,0,126,0,0,0,20,0,0,0},
		{0,0,0,0,64,0,64,0,64,0,64,0,64,0,64,0,64,0,64,0,64,0,0,0,64,0,-128,0},
		{0,0,0,0,64,0,64,0,64,0,64,0,64,0,64,0,64,0,64,0,64,0,0,0,64,0,32,0},
		{0,0,0,0,64,0,64,0,64,0,64,0,64,0,64,0,64,0,64,0,64,0,0,0,-96,0,64,0},
		{0,0,0,0,64,0,64,0,64,0,64,0,64,0,64,0,64,0,64,0,64,0,0,0,-96,0,0,0},
		{0,0,0,0,124,0,66,0,65,0,65,0,-15,0,65,0,65,0,66,0,124,0,0,0,0,0,0,0},
		{0,0,0,0,65,0,67,0,69,0,69,0,73,0,81,0,81,0,97,0,65,0,0,0,22,0,26,0},
		{0,0,0,0,28,0,34,0,65,0,65,0,65,0,65,0,65,0,34,0,28,0,0,0,4,0,8,0},
		{0,0,0,0,28,0,34,0,65,0,65,0,65,0,65,0,65,0,34,0,28,0,0,0,8,0,4,0},
		{0,0,0,0,28,0,34,0,65,0,65,0,65,0,65,0,65,0,34,0,28,0,0,0,20,0,8,0},
		{0,0,0,0,28,0,34,0,65,0,65,0,65,0,65,0,65,0,34,0,28,0,0,0,22,0,26,0},
		{0,0,0,0,28,0,34,0,65,0,65,0,65,0,65,0,65,0,34,0,28,0,0,0,20,0,0,0},
		{0,0,0,0,65,0,34,0,20,0,8,0,20,0,34,0,65,0,0,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,92,0,34,0,81,0,81,0,73,0,69,0,69,0,34,0,29,0,0,0,0,0,0,0},
		{0,0,0,0,60,0,66,0,66,0,66,0,66,0,66,0,66,0,66,0,66,0,0,0,8,0,16,0},
		{0,0,0,0,60,0,66,0,66,0,66,0,66,0,66,0,66,0,66,0,66,0,0,0,16,0,8,0},
		{0,0,0,0,60,0,66,0,66,0,66,0,66,0,66,0,66,0,66,0,66,0,0,0,20,0,8,0},
		{0,0,0,0,60,0,66,0,66,0,66,0,66,0,66,0,66,0,66,0,66,0,0,0,20,0,0,0},
		{0,0,0,0,16,0,16,0,16,0,16,0,16,0,40,0,40,0,68,0,-126,0,0,0,16,0,8,0},
		{0,0,0,0,64,0,64,0,120,0,68,0,68,0,68,0,120,0,64,0,64,0,0,0,0,0,0,0},
		{0,0,0,0,88,0,68,0,68,0,72,0,80,0,80,0,72,0,72,0,48,0,0,0,0,0,0,0},
		{0,0,0,0,62,0,68,0,68,0,60,0,4,0,68,0,56,0,0,0,8,0,16,0,0,0,0,0},
		{0,0,0,0,62,0,68,0,68,0,60,0,4,0,68,0,56,0,0,0,32,0,16,0,0,0,0,0},
		{0,0,0,0,62,0,68,0,68,0,60,0,4,0,68,0,56,0,0,0,40,0,16,0,0,0,0,0},
		{0,0,0,0,62,0,68,0,68,0,60,0,4,0,68,0,56,0,0,0,44,0,52,0,0,0,0,0},
		{0,0,0,0,62,0,68,0,68,0,60,0,4,0,68,0,56,0,0,0,40,0,0,0,0,0,0,0},
		{0,0,0,0,62,0,68,0,68,0,60,0,4,0,68,0,56,0,0,0,28,0,20,0,28,0,0,0},
		{0,0,0,0,55,-128,72,0,72,0,63,-128,8,-128,72,-128,55,0,0,0,0,0,0,0,0,0,0,0},
		{8,0,16,0,56,0,64,0,64,0,64,0,64,0,64,0,56,0,0,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,60,0,64,0,64,0,124,0,68,0,68,0,56,0,0,0,8,0,16,0,0,0,0,0},
		{0,0,0,0,60,0,64,0,64,0,124,0,68,0,68,0,56,0,0,0,16,0,8,0,0,0,0,0},
		{0,0,0,0,60,0,64,0,64,0,124,0,68,0,68,0,56,0,0,0,40,0,16,0,0,0,0,0},
		{0,0,0,0,60,0,64,0,64,0,124,0,68,0,68,0,56,0,0,0,40,0,0,0,0,0,0,0},
		{0,0,0,0,64,0,64,0,64,0,64,0,64,0,64,0,64,0,0,0,64,0,-128,0,0,0,0,0},
		{0,0,0,0,64,0,64,0,64,0,64,0,64,0,64,0,64,0,0,0,64,0,32,0,0,0,0,0},
		{0,0,0,0,64,0,64,0,64,0,64,0,64,0,64,0,64,0,0,0,-96,0,64,0,0,0,0,0},
		{0,0,0,0,64,0,64,0,64,0,64,0,64,0,64,0,64,0,0,0,-96,0,0,0,0,0,0,0},
		{0,0,0,0,56,0,68,0,68,0,68,0,68,0,68,0,56,0,40,0,112,0,8,0,0,0,0,0},
		{0,0,0,0,68,0,68,0,68,0,68,0,68,0,100,0,88,0,0,0,44,0,52,0,0,0,0,0},
		{0,0,0,0,56,0,68,0,68,0,68,0,68,0,68,0,56,0,0,0,16,0,32,0,0,0,0,0},
		{0,0,0,0,56,0,68,0,68,0,68,0,68,0,68,0,56,0,0,0,16,0,8,0,0,0,0,0},
		{0,0,0,0,56,0,68,0,68,0,68,0,68,0,68,0,56,0,0,0,40,0,16,0,0,0,0,0},
		{0,0,0,0,56,0,68,0,68,0,68,0,68,0,68,0,56,0,0,0,44,0,52,0,0,0,0,0},
		{0,0,0,0,56,0,68,0,68,0,68,0,68,0,68,0,56,0,0,0,40,0,0,0,0,0,0,0},
		{0,0,0,0,8,0,0,0,0,0,127,0,0,0,0,0,8,0,0,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,120,0,68,0,100,0,84,0,76,0,68,0,60,0,0,0,0,0,0,0,0,0,0,0},
		{0,0,0,0,52,0,76,0,68,0,68,0,68,0,68,0,68,0,0,0,16,0,32,0,0,0,0,0},
		{0,0,0,0,52,0,76,0,68,0,68,0,68,0,68,0,68,0,0,0,16,0,8,0,0,0,0,0},
		{0,0,0,0,52,0,76,0,68,0,68,0,68,0,68,0,68,0,0,0,40,0,16,0,0,0,0,0},
		{0,0,0,0,52,0,76,0,68,0,68,0,68,0,68,0,68,0,0,0,40,0,0,0,0,0,0,0},
		{32,0,16,0,16,0,40,0,40,0,68,0,68,0,-126,0,-126,0,0,0,16,0,8,0,0,0,0,0},
		{64,0,64,0,92,0,98,0,66,0,66,0,66,0,98,0,92,0,64,0,64,0,0,0,0,0,0,0},
		{32,0,16,0,16,0,40,0,40,0,68,0,68,0,-126,0,-126,0,0,0,40,0,0,0,0,0,0,0},
	};
	
	/**
	 * The AdvanceX value for each character (autogenerated from
	 * default "Sans Serif" 14 font).
	 */
	static final float[] fontAdvance = new float[] {
		9,9,9,9,9,9,9,9,9,0,0,9,9,0,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,
		4,4,4,8,8,8,8,3,4,4,6,10,4,7,4,6,8,8,8,8,8,8,8,8,8,8,4,4,10,10,10,5,
		10,8,7,8,9,7,6,9,9,3,4,8,6,10,9,9,7,9,8,6,8,8,8,10,8,7,7,4,6,4,8,6,
		7,7,8,6,8,7,4,7,7,3,4,7,3,11,7,7,8,8,5,6,4,7,6,9,7,6,7,4,4,4,8,9,
		9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,
		4,4,8,8,8,8,4,8,7,10,6,6,10,7,8,6,5,10,5,5,7,8,8,4,7,5,6,6,10,10,10,5,
		8,8,8,8,8,8,11,8,7,7,7,7,3,3,3,3,9,9,9,9,9,9,9,10,9,8,8,8,8,7,7,7,
		7,7,7,7,7,7,10,6,7,7,7,7,3,3,3,3,7,7,7,7,7,7,7,10,7,7,7,7,7,6,8,6
	};
	
	static class MultisampleChooser extends DefaultGLCapabilitiesChooser {
	    public int chooseCapabilities(GLCapabilities desired,
	                                  GLCapabilities[] available,
	                                  int windowSystemRecommendedChoice) {
	      boolean anyHaveSampleBuffers = false;
	      for (int i = 0; i < available.length; i++) {
	        GLCapabilities caps = available[i];
	        if (caps != null && caps.getSampleBuffers()) {
	          anyHaveSampleBuffers = true;
	          break;
	        }
	      }
	      int selection = super.chooseCapabilities(desired, available, windowSystemRecommendedChoice);
	      if (!anyHaveSampleBuffers) {
	        System.err.println("WARNING: antialiasing will be disabled because none of the available pixel formats had it to offer");
	      } else {
	        if (!available[selection].getSampleBuffers()) {
	          System.err.println("WARNING: antialiasing will be disabled because the DefaultGLCapabilitiesChooser didn't supply it");
	        }
	      }
	      return selection;
	    }
	  }
	
	private final static float BONE_LENGTH = 1.0f;
	private final static float BONE_WIDTH = 0.1f;
	private final static GlMaterial BONE_MATERIAL = new GlMaterial(new Color3f(), 0.25f, 0.0f, 10);
	
	private final static Shape BONE = new Shape(
			new Point3f[] {
					new Point3f(0, 0, 0),
					new Point3f(BONE_WIDTH, 0, BONE_WIDTH),
					new Point3f(0, BONE_WIDTH, BONE_WIDTH),
					new Point3f(-BONE_WIDTH, 0, BONE_WIDTH),
					new Point3f(0,-BONE_WIDTH, BONE_WIDTH),
					new Point3f(0, 0, BONE_LENGTH),
			},
			new int[] { 0, 2, 1, 0, 3, 2, 0, 4, 3, 0, 1, 4, 5, 1, 2, 5, 2, 3, 5, 3, 4, 5, 4, 1 }
	);
	
	/** Offset to the GL Display-Lists holding the character bitmaps. */
	private int fontOffset;
	
	private int maxLights, maxTextureSize;
	
	GLEventListener glEventListener;
	
	private final FloatBuffer buffer = BufferUtil.newFloatBuffer(SdsConstants.MAX_VALENCE * 12 + 12);
	
	public ViewportGl(int id, ViewDirection direction, CollectionAttr<ViewDirection> orthoDirections, JPatchInspector inspector) {
		super(id, direction, orthoDirections, inspector);
		
		GLCapabilities caps = new GLCapabilities();
	    GLCapabilitiesChooser chooser = new MultisampleChooser();

	    caps.setSampleBuffers(antialiasAttr.getBoolean());
	    caps.setNumSamples(4);
	    drawable = new GLCanvas(caps, chooser, null, null);
	    
	    
//		drawable = LIGHTWEIGHT ? new GLJPanel(caps) : new GLCanvas(caps);
		component = (Component) drawable;
		component.setBackground(COLORS.background.get());
		
		glEventListener = new GLEventListener() {

			public void init(GLAutoDrawable drawable) {
//				System.out.println("GL init");
				drawable.setGL(new DebugGL(drawable.getGL()));
				gl = drawable.getGL();
//				gl.glEnd();
				
				/* Generate display lists to render font characters. */
				gl.glPixelStorei(GL.GL_UNPACK_ALIGNMENT, 1);
				fontOffset = gl.glGenLists(256);
				for (int i = 0; i < 256; i++) {
			        gl.glNewList(i + fontOffset, GL_COMPILE);
			            gl.glBitmap(16, 12, 0, 0, fontAdvance[i], 0, fontRaster[i], 0);
			        gl.glEndList();
			    }
				
				/* retrieve GL_MAX_LIGHTS and GL_MAX_TEXTURE_SIZE */
				int[] I = new int[1];
				gl.glGetIntegerv(GL_MAX_LIGHTS, I, 0);
				maxLights = I[0];
				gl.glGetIntegerv(GL_MAX_TEXTURE_SIZE, I, 0);
				maxTextureSize = I[0];
				
				setLighting(RealtimeLighting.createThreepointLight());			
//				setLighting(RealtimeLighting.createHeadLight());
				
//				gl.glHint(GL_MULTISAMPLE_FILTER_HINT_NV, GL_NICEST);
				
				
				gl.glEnable(GL_POLYGON_OFFSET_FILL);
				gl.glPolygonOffset(1.0f, 1.0f);
				gl.glDisable(GL_DEPTH_TEST);
				gl.glDisable(GL_NORMALIZE);
				gl.glEnable(GL_CULL_FACE);
				gl.glCullFace(GL_BACK);
//				gl.glFrontFace(GL_CW);	// left handed
				canUseProgram = gl.isFunctionAvailable("glUseProgram");
				canUseProgram = false;
				if (canUseProgram) {
					int vertexShader = gl.glCreateShader(GL_VERTEX_SHADER);
					try {
						loadShader(ClassLoader.getSystemResourceAsStream("glsl/perPixelLight.vs"), gl, vertexShader);
					} catch (IOException e) {
						e.printStackTrace();
					}
					gl.glCompileShader(vertexShader);
					printShaderInfo(gl, vertexShader);
					
					int fragmentShader = gl.glCreateShader(GL_FRAGMENT_SHADER);
					try {
						loadShader(ClassLoader.getSystemResourceAsStream("glsl/perPixelLight.fs"), gl, fragmentShader);
					} catch (IOException e) {
						e.printStackTrace();
					}
					gl.glCompileShader(fragmentShader);
					printShaderInfo(gl, fragmentShader);
					
					program = gl.glCreateProgram();
					gl.glAttachShader(program, vertexShader);
					gl.glAttachShader(program, fragmentShader);
					gl.glLinkProgram(program);
					gl.glUseProgram(program);
					printProgramInfo(gl, program);
					gl.glUseProgram(0);
				}
			}

			public void display(GLAutoDrawable drawable) {
//				System.out.println("GL display " + this + " " + repaintCount++);
//				long t = System.currentTimeMillis();
//				gl.glFlush();
//				gl.glFinish();	// wait for previous gl functions to finish
				Color3f background = active ? COLORS.activeBackground : COLORS.background;
				gl.glClearColor(background.x, background.y, background.z, 0);	// set background color
//				gl.glClearDepth(farClip);									// set initial depth-buffer value
				gl.glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);	// clear color and depth buffers
//				gl.glFlush();
//				gl.glFinish();
				draw();
//				gl.glFlush();
//				gl.glFinish();
//				System.out.println("GL display on thread " + Thread.currentThread());
//				System.out.println(System.currentTimeMillis() - t);
			}

			public void reshape(GLAutoDrawable drawable, int x, int y, int width, int height) {
//				System.out.println("GL reshape");
//				viewDef.computeMatrix();
//				init(drawable);
//				display(drawable);
			}

			public void displayChanged(GLAutoDrawable drawable, boolean modeChanged, boolean deviceChanged) {
//				System.out.println("GL displayChanged");
			}
		};
		
		drawable.addGLEventListener(glEventListener);
		
//		component.addMouseWheelListener(new MouseWheelListener() {
//			public void mouseWheelMoved(MouseWheelEvent e) {
//				subdivLevel += e.getWheelRotation();
//				if (subdivLevel < 1) subdivLevel = 1;
//				if (subdivLevel > 6) subdivLevel = 6;
//				
//				useProgram = !useProgram;
//
//				component.repaint();
//			}
//		});
	}
	
//	public void display() {
//		drawable.
//	}

	public GL getGl() {
		return gl;
	}
	
//	@Override
//	public void drawShape(Shape s) {
//		gl.glShadeModel(GL_SMOOTH);
//		gl.glEnable(GL_LIGHTING);
//		gl.glBegin(GL_TRIANGLES);
//		for (int i = 0, n = s.meshes.length; i < n; i++) {
//			drawTriangleMesh(s.meshes[i]);
//		}
//		gl.glEnd();
//		gl.glDisable(GL_LIGHTING);
//		gl.glEnable(GL_LINE_SMOOTH);
//		gl.glEnable(GL_BLEND);
//		gl.glBegin(GL_LINES);
//		for (int i = 0, n = s.wires.length; i < n; i++) {
//			drawWireFrame(s.wires[i]);
//		}
//		gl.glEnd();
//		gl.glDisable(GL_BLEND);
//		gl.glDisable(GL_LINE_SMOOTH);
//	}
	
	public void setMaterial(int side, float[] array) {
		gl.glDisable(GL_COLOR_MATERIAL);
		gl.glMaterialfv(side, GL_AMBIENT, array, GlMaterial.AMBIENT);
		gl.glMaterialfv(side, GL_DIFFUSE, array, GlMaterial.DIFFUSE);
		gl.glMaterialfv(side, GL_SPECULAR, array, GlMaterial.SPECULAR);
		gl.glMaterialfv(side, GL_EMISSION, array, GlMaterial.EMISSION);
		gl.glMaterialfv(side, GL_SHININESS, array, GlMaterial.SHININESS);
		gl.glEnable(GL_COLOR_MATERIAL);
	}
	
//	private void drawTriangleMesh(TriangleMesh t) {
//		setMaterial(GL_FRONT, t.m.getArray());
//		Matrix4d matrix = viewDef.getMatrix();
//		
//		for (int i = 0, n = t.t.length; i < n; i++) {
//			p.set(t.v[t.t[i]]);
//			v.set(t.n[t.t[i]]);
//			matrix.transform(p);
//			matrix.transform(v);
//			v.normalize();
//			gl.glNormal3f(v.x, v.y, v.z);
//			gl.glVertex3f(p.x, p.y, p.z);
//		}
//	}
//	
//	private void drawWireFrame(WireFrame w) {
//		gl.glColor4fv(w.array, 0);
//		Matrix4d matrix = viewDef.getMatrix();
//		for (int i = 0, n = w.l.length; i < n; i++) {
//			p.set(w.v[w.l[i]]);
//			matrix.transform(p);
//			gl.glVertex3f(p.x, p.y, p.z);
//		}
//	}
	
	@Override
	public void draw() {
		if (antialiasAttr.getBoolean()) {
			gl.glEnable(GL_MULTISAMPLE);
		} else {
			gl.glDisable(GL_MULTISAMPLE);
		}
		viewDef.configureTransformUtil(transformUtil);
		time = System.nanoTime();
//		System.out.println("ViewportGL.draw() at " + System.currentTimeMillis());
//		if (true) return;
//		rasterMode();
//		drawGrid();
		spatialMode();
//		gl.glPolygonMode(GL_FRONT_AND_BACK, GL_LINE);
		gl.glColor3f(0, 0, 0);
		gl.glShadeModel(GL_SMOOTH);
		gl.glDisable(GL_COLOR_MATERIAL);
		gl.glEnable(GL_LIGHTING);
		gl.glEnable(GL_NORMALIZE);
		
//		if (true) return;
		
//		gl.glEnable(GL_BLEND);
//		Matrix4d m = new Matrix4d();
//		TriangleMesh cx = TriangleMesh.createCone(16, new GlMaterial(new Color3f(0.4f, 0, 0), new Color3f(0.8f, 0, 0), new Color3f(0, 0, 0), 0));
//		TriangleMesh cy = TriangleMesh.createCone(16, new GlMaterial(new Color3f(0, 0.4f, 0), new Color3f(0, 0.8f, 0), new Color3f(0, 0, 0), 0));
//		TriangleMesh cz = TriangleMesh.createCone(16, new GlMaterial(new Color3f(0.2f, 0.2f, 0.4f), new Color3f(0.4f, 0.4f, 0.8f), new Color3f(0, 0, 0), 0));
//		m.set(new double[] {
//				0, 0, 0.2, 0.9,
//				0, 0.2, 0, 0,
//				0.2, 0, 0, 0,
//				0, 0, 0, 1
//		});
//		cx.transform(m);
//		m.set(new double[] {
//				0.2, 0, 0, 0,
//				0, 0, 0.2, 0.9,
//				0, 0.2, 0, 0,Matrix4f
//				0, 0, 0, 1
//		});
//		cy.transform(m);
//		m.set(new double[] {
//				0.2, 0, 0, 0,
//				0, 0.2, 0, 0,
//				0, 0, 0.2, 0.9,
//				0, 0, 0, 1
//		});
//		cz.transform(m);
//		WireFrame wx = new WireFrame(new Point3d[] { new Point3d(0, 0, 0), new Point3d(1, 0, 0) }, new int[] { 0, 1 }, new Color3f(1, 0, 0));
//		WireFrame wy = new WireFrame(new Point3d[] { new Point3d(0, 0, 0), new Point3d(0, 1, 0) }, new int[] { 0, 1 }, new Color3f(0, 1, 0));
//		WireFrame wz = new WireFrame(new Point3d[] { new Point3d(0, 0, 0), new Point3d(0, 0, 1) }, new int[] { 0, 1 }, new Color3f(0.5f, 0.5f, 1));
//		
//		Shape s = new Shape(new TriangleMesh[] { cx, cy, cz }, new WireFrame[] { wx, wy, wz } );
		
//		drawShape(s);
		
//		for (Model model : models) {
//			drawModel(model);
//		}
		
//		gl.glPolygonMode(GL_FRONT, GL_LINE);
//		drawSds(Main.getInstance().getActiveSds());
//		Sds activeSds = Main.getInstance().getActiveSds();
//		if (activeSds != null) {
//			drawSds3(activeSds);
//		}
		
//		Matrix4d cameraMatrix = viewDef.getMatrix(new Matrix4d());	// TODO: write better implementation 
//		transformUtil.setCamera2World(cameraMatrix);
		
//		drawOrigin(viewDef.getTransformUtil().getMatrix(WORLD, CAMERA, new Matrix4f()));
		
		SceneGraphNode sceneGraphRoot = Main.getInstance().getSceneGraphRoot();
		drawSceneGraphElement(sceneGraphRoot);
		Selection selection = Main.getInstance().getSelection();
		drawSelection(selection);
		
		JPatchTool tool = Main.getInstance().getActiveTool();
//		System.out.println("tool = " + tool);
		gl.glMatrixMode(GL_MODELVIEW);
		gl.glLoadIdentity();
		if (tool != null) {
			tool.draw(this);
		}
		rasterMode();
		if (showNodeNamesAttr.getBoolean()) {
			drawSceneGraphNames(sceneGraphRoot);
		}
		drawInfo();
//		gl.glFlush(); // ensure that everything gets drawn
//		gl.glFinish();
	}
	
	private void drawSceneGraphElement(SceneGraphNode node) {
		
//		System.out.println("drawing " + node + " " + (node == null ? "(null)" : "(not null)"));
//		Matrix4d matrix = new Matrix4d(viewDef.getMatrix(new Matrix4d()));
//		Transform transform = node.getTransform();
		
		if (node instanceof XFormNode) {
			((XFormNode) node).getLocal2WorldTransform(transformUtil, LOCAL);
		} else {
			transformUtil.setSpace2World(TransformUtil.LOCAL, IDENTITY);
		}
		
//		for (int i = 0; i < 4; i++) {
//			for (int j = 0; j < 4; j++) {
//				System.out.print(modelView[i + j * 4] + " \t");
//			}
//			System.out.println();
//		}
//		System.out.println();
		
//		if (transform != null) {
//			transformUtil.setTransform(LOCAL, transform);
////			transform.mul2(matrix);
////			transform.getMatrix(m);
////			if (node instanceof TransformNode) {
////				System.out.println("sceneGraph TransformNode @ " + ((TransformNode) node).getNameAttribute().getValue());
////				System.out.println(modelViewMatrix);
////			}
////			modelViewMatrix.set(matrix);
////			matrix.mul(m);
////			m.mul(matrix);
////			matrix.mul(m);
////			modelViewMatrix.mul(matrix);
//		} else {
//			transformUtil.setSpace2World(TransformUtil.LOCAL, IDENTITY);
//		}
//		modelView.set(matrix);
		
		transformUtil.getMatrix(TransformUtil.LOCAL, TransformUtil.CAMERA, modelView);
		gl.glMatrixMode(GL_MODELVIEW);
		gl.glLoadIdentity();
		gl.glLoadMatrixd(modelView, 0);
		
		drawOrigin();
		if (node instanceof SdsModel) {
			drawSds2(((SdsModel) node).getSds(), 2);
		}
		if (node instanceof Bone) {
			Bone bone = (Bone) node;
			double length = bone.getLengthAttribute().getDouble();
			modelView[0] *= length;
			modelView[1] *= length;
			modelView[2] *= length;
			modelView[4] *= length;
			modelView[5] *= length;
			modelView[6] *= length;
			modelView[8] *= length;
			modelView[9] *= length;
			modelView[10] *= length;
			Color3f color = bone.getColor(new Color3f()); // TODO reuse color object
			gl.glEnable(GL_LIGHTING);
			gl.glShadeModel(GL_SMOOTH);
			gl.glPolygonMode(GL_FRONT, GL_FILL);
			gl.glColor3f(0, 0, 0);
			gl.glDisable(GL_COLOR_MATERIAL);
			color.scale(0.8f);
			BONE_MATERIAL.setKd(color);
			color.scale(0.25f);
			BONE_MATERIAL.setKa(color);
			BONE_MATERIAL.applyMaterial(gl, GL_FRONT);
			BONE.draw(gl);
			gl.glEnable(GL_DEPTH_TEST);
		}
		for (SceneGraphNode child : node.getChildrenAttribute().getElements()) {
			drawSceneGraphElement(child);
		}
		
	}
	
	private void drawSceneGraphNames(SceneGraphNode node) {
		if (node instanceof XFormNode) {
			((XFormNode) node).getLocal2WorldTransform(transformUtil, LOCAL);
		} else {
			transformUtil.setSpace2World(TransformUtil.LOCAL, IDENTITY);
		}
		Point3d p = new Point3d();
		transformUtil.projectToScreen(LOCAL, p, p);
		if (node instanceof XFormNode) {
			if (!transformUtil.isPerspective() || p.z > nearClip) {
				drawString(((XFormNode) node).getNameAttribute().getValue(), (int) p.x, (int) p.y);
			}
		}
		for (SceneGraphNode child : node.getChildrenAttribute().getElements()) {
			drawSceneGraphNames(child);
		}
	}
	
//	public void setMaterial(Color3f ka) {
//		gl.glMaterialfv(side, GL_AMBIENT, new float[] { mp.red * mp.ambient, mp.green * mp.ambient, mp.blue * mp.ambient, 1 } );
//		gl.glMaterialfv(side, GL_DIFFUSE, new float[] { mp.red * mp.diffuse, mp.green * mp.diffuse, mp.blue * mp.diffuse, 1 } );
//		gl.glMaterialfv(side, GL_SPECULAR, new float[] {
//				mp.specular * (1 - mp.metallic + mp.metallic * mp.red),
//				mp.specular * (1 - mp.metallic + mp.metallic * mp.green),
//				mp.specular * (1 - mp.metallic + mp.metallic * mp.blue),
//				1.0f });
//		gl.glMaterialfv(side, GL_SHININESS, new float[] { 1f / mp.roughness } );
//	}
	
	public void setLighting(RealtimeLighting lighting) {
		Color3f ambient = lighting.getAmbientColor();
		gl.glLightModelfv(GL_LIGHT_MODEL_AMBIENT, new float[] { ambient.x, ambient.y, ambient.z, 1 }, 0);
		for (int i = 0; i < maxLights; i++) {
			if (i < lighting.numLights()) {
				gl.glEnable(GL_LIGHT0 + i);
				RealtimeLighting.LightSource light = lighting.getLight(i);
				if (light instanceof RealtimeLighting.DirectionalLight) {
					RealtimeLighting.DirectionalLight directionalLight = (RealtimeLighting.DirectionalLight) light;
					Color3f color = directionalLight.getColor();
					
					/*
					 * set GL light colors
					 */
					gl.glLightfv(GL_LIGHT0 + i, GL_AMBIENT, new float[] { 0, 0, 0, 1 }, 0);
					gl.glLightfv(GL_LIGHT0 + i, GL_DIFFUSE, new float[] { color.x, color.y, color.z, 1 }, 0);
					if (directionalLight.castsHighlight())
						gl.glLightfv(GL_LIGHT0 + i, GL_SPECULAR, new float[] { color.x, color.y, color.z, 1 }, 0);
					else
						gl.glLightfv(GL_LIGHT0 + i, GL_SPECULAR, new float[] { 0, 0, 0, 1 }, 0);
					Vector3f direction = directionalLight.getTransformedDirection();
					
					/*
					 * set GL light directions (w = 0 for directional light)
					 */
					gl.glLightfv(GL_LIGHT0 + i, GL_POSITION, new float[] { direction.x, direction.y, direction.z, 0 }, 0);
					
					/*
					 * set GL spot cutoff (180 = no spot)
					 */
					gl.glLightf(GL_LIGHT0 + i, GL_SPOT_CUTOFF, 180);
				} else if (light instanceof RealtimeLighting.PointLight) {
					RealtimeLighting.PointLight pointLight = (RealtimeLighting.PointLight) light;
					Color3f color = pointLight.getColor();
					
					/*
					 * set GL light colors
					 */
					gl.glLightfv(GL_LIGHT0 + i, GL_AMBIENT, new float[] { 0, 0, 0, 1 }, 0);
					gl.glLightfv(GL_LIGHT0 + i, GL_DIFFUSE, new float[] { color.x, color.y, color.z, 1 }, 0);
					if (pointLight.castsHighlight())
						gl.glLightfv(GL_LIGHT0 + i, GL_SPECULAR, new float[] { color.x, color.y, color.z, 1 }, 0);
					else
						gl.glLightfv(GL_LIGHT0 + i, GL_SPECULAR, new float[] { 0, 0, 0, 1 }, 0);
					Point3f position = pointLight.getTransformedPosition();
					
					/*
					 * set GL light position (w = 1 for point light)
					 */
					gl.glLightfv(GL_LIGHT0 + i, GL_POSITION, new float[] { position.x, position.y, position.z, 1 }, 0);
					
					/*
					 * set GL attenuation
					 */
					switch (pointLight.getAttenuation()) {
						case 0: {
							gl.glLightf(GL_LIGHT0 + i, GL_CONSTANT_ATTENUATION, 1);
							gl.glLightf(GL_LIGHT0 + i, GL_LINEAR_ATTENUATION, 0);
							gl.glLightf(GL_LIGHT0 + i, GL_QUADRATIC_ATTENUATION, 0);
						} break;
						case 1: {
							gl.glLightf(GL_LIGHT0 + i, GL_CONSTANT_ATTENUATION, 0);
							gl.glLightf(GL_LIGHT0 + i, GL_LINEAR_ATTENUATION, 1f / pointLight.getDistance());
							gl.glLightf(GL_LIGHT0 + i, GL_QUADRATIC_ATTENUATION, 0);
						} break;
						case 2: {
							gl.glLightf(GL_LIGHT0 + i, GL_CONSTANT_ATTENUATION, 0);
							gl.glLightf(GL_LIGHT0 + i, GL_LINEAR_ATTENUATION, 0);
							gl.glLightf(GL_LIGHT0 + i, GL_QUADRATIC_ATTENUATION, 1f / pointLight.getDistance() / pointLight.getDistance());
						} break;
					}
					
					/*
					 * set GL spot cutoff (180 = no spot)
					 */
					gl.glLightf(GL_LIGHT0 + i, GL_SPOT_CUTOFF, 180);
				} else if (light instanceof RealtimeLighting.SpotLight) {
					RealtimeLighting.SpotLight spotLight = (RealtimeLighting.SpotLight) light;
					Color3f color = spotLight.getColor();
					
					/*
					 * set GL light colors
					 */
					gl.glLightfv(GL_LIGHT0 + i, GL_AMBIENT, new float[] { 0, 0, 0, 1 }, 0);
					gl.glLightfv(GL_LIGHT0 + i, GL_DIFFUSE, new float[] { color.x, color.y, color.z, 1 }, 0);
					if (spotLight.castsHighlight())
						gl.glLightfv(GL_LIGHT0 + i, GL_SPECULAR, new float[] { color.x, color.y, color.z, 1 }, 0);
					else
						gl.glLightfv(GL_LIGHT0 + i, GL_SPECULAR, new float[] { 0, 0, 0, 1 }, 0);
					Point3f position = spotLight.getTransformedPosition();
					
					/*
					 * set GL light position (w = 1 for point light)
					 */
					gl.glLightfv(GL_LIGHT0 + i, GL_POSITION, new float[] { position.x, position.y, position.z, 1 }, 0);
					
					/*
					 * set GL attenuation
					 */
					switch (spotLight.getAttenuation()) {
						case 0: {
							gl.glLightf(GL_LIGHT0 + i, GL_CONSTANT_ATTENUATION, 1);
							gl.glLightf(GL_LIGHT0 + i, GL_LINEAR_ATTENUATION, 0);
							gl.glLightf(GL_LIGHT0 + i, GL_QUADRATIC_ATTENUATION, 0);
						} break;
						case 1: {
							gl.glLightf(GL_LIGHT0 + i, GL_CONSTANT_ATTENUATION, 0);
							gl.glLightf(GL_LIGHT0 + i, GL_LINEAR_ATTENUATION, 1f / spotLight.getDistance());
							gl.glLightf(GL_LIGHT0 + i, GL_QUADRATIC_ATTENUATION, 0);
						} break;
						case 2: {
							gl.glLightf(GL_LIGHT0 + i, GL_CONSTANT_ATTENUATION, 0);
							gl.glLightf(GL_LIGHT0 + i, GL_LINEAR_ATTENUATION, 0);
							gl.glLightf(GL_LIGHT0 + i, GL_QUADRATIC_ATTENUATION, 1f / spotLight.getDistance() / spotLight.getDistance());
						} break;
					}
					
					Vector3f direction = spotLight.getTransformedDirection();
					
					/*
					 * set GL spot direction
					 */
					gl.glLightfv(GL_LIGHT0 + i, GL_SPOT_DIRECTION, new float[] { direction.x, direction.y, direction.z }, 0);
					
					/*
					 * set GL spot cutoff
					 */
					gl.glLightf(GL_LIGHT0 + i, GL_SPOT_CUTOFF, spotLight.getRadius());
					
					/*
					 * set GL spot cutoff exponent
					 */
					gl.glLightf(GL_LIGHT0 + i, GL_SPOT_EXPONENT, 0);
				}
			} else {
				gl.glDisable(GL_LIGHT0 + i);
			}
		}
	}
	
//	@Override
//	protected void drawGrid() {
//		double scale = viewTypeAttr.getValue()..getDouble();
//		double width = component.getWidth();
//		double height = component.getHeight();
//		double matrixScale = scale / 20 * width;
//		double u = 1000 / scale / width;
//		double majorSpacing = (float) Math.pow(10, Math.floor(Math.log10(u)));
//		double screenSpacing = majorSpacing * matrixScale;
//		double xCenter = (float) matrix.m03 + width / 2;
//		double yCenter = (float) matrix.m13 + height / 2;
//		float r = COLORS.majorGrid.x;
//		float g = COLORS.majorGrid.y;
//		float b = COLORS.majorGrid.z;
////		float r0 = COLORS.minorGrid.x;
////		float g0 = COLORS.minorGrid.y;
////		float b0 = COLORS.minorGrid.z;
//		float a;
////		System.out.println("majorSpacing=" + majorSpacing + " screenSpacing=" + screenSpacing);
//		
//		gl.glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA);
//		gl.glEnable(GL_BLEND);
//		gl.glBegin(GL_LINES);
//		
//		double spacing;
////		System.out.println("screenSpacing=" + screenSpacing);
//		for (int pass = 0; pass < 3; pass++) {
//			switch(pass) {
//			case 0:
//				spacing = screenSpacing / 2; // 2.5 - 25
//				a = (float) (Math.min(1, Math.max(0, (spacing - 5) / 2)) * 0.5 +
//					Math.min(1, Math.max(0, (spacing - 20) / 5)) * 0.5);
////				r = 1; g = 0; b = 0;
//				break;
//			case 1:
//				spacing = screenSpacing; // 5..50
//				a = (float) (Math.min(1, Math.max(0, (spacing - 5) / 5)) * 0.5 +
//					Math.min(1, Math.max(0, (spacing - 40) / 10)) * 0.5);
////				r = 0; g = 1; b = 0;
//				break;
//			default:
//				spacing = screenSpacing * 5; // 20..250
////				a = Math.min(1, Math.max(0, (spacing - 100) / 50)) * 0.5f +
////					Math.min(1, Math.max(0, (spacing - 400) / 50)) * 0.5f;
//				a = 1;
////				r = 1; g = 1; b = 1;
//				break;
//			}
//			if (spacing < 5) {
//				continue;
//			}
//			
//			gl.glColor4f(r, g, b, a);
//			//gl.glColor4f(r1 * b + r0 * (1 - b), g1 * b + g0 * (1 - b), b1 * b + b0 * (1 - b), a);
//			
//			int xStart = (int) Math.round(-xCenter / spacing);
//			int xEnd = (int) Math.round((width - xCenter) / spacing);
//			int yStart = (int) Math.round(-yCenter / spacing);
//			int yEnd = (int) Math.round((height - yCenter) / spacing);
//			for (int x = xStart; x <= xEnd; x++) {
//				gl.glVertex2d(xCenter + x * spacing, 0);
//				gl.glVertex2d(xCenter + x * spacing, height);
//			}
//			for (int y = yStart; y <= yEnd; y++) {
//				gl.glVertex2d(0, height - yCenter - y * spacing);
//				gl.glVertex2d(width, height - yCenter - y * spacing);
//			}
//		}
//		gl.glEnd();
//		gl.glDisable(GL_BLEND);
//	}

	protected void drawOrigin() {
		float radius = (float) transformUtil.computeNiceRadius(-modelView[11], component.getWidth(), component.getHeight()) / 2;
		Point3f p0 = new Point3f(0, 0, 0);
		Point3f px = new Point3f(radius, 0, 0);
		Point3f py = new Point3f(0, radius, 0);
		Point3f pz = new Point3f(0, 0, radius);
	
		
//		System.out.println("p0 = " + p0);
//		System.out.println("px = " + px);
//		System.out.println("py = " + py);
//		System.out.println("pz = " + pz);
		
		gl.glDisable(GL_LIGHTING);
		gl.glBegin(GL_LINES);
		gl.glColor3f(1, 0, 0);
		gl.glVertex3f(p0.x, p0.y, p0.z);
		gl.glVertex3f(px.x, px.y, px.z);
		gl.glColor3f(0, 1, 0);
		gl.glVertex3f(p0.x, p0.y, p0.z);
		gl.glVertex3f(py.x, py.y, py.z);
		gl.glColor3f(0, 0, 1);
		gl.glVertex3f(p0.x, p0.y, p0.z);
		gl.glVertex3f(pz.x, pz.y, pz.z);
		gl.glEnd();
		
//		gl.glDisable(GL_CULL_FACE);
//		for (int z = 0; z < 3; z++) {
//			Point3f a = new Point3f(-1, 1, z);
//			Point3f b = new Point3f( 1, 1, z);
//			Point3f c = new Point3f( 1,-1, z);
//			Point3f d = new Point3f(-1,-1, z);
//			transformUtil.world2Camera(a, a);
//			transformUtil.world2Camera(b, b);
//			transformUtil.world2Camera(c, c);
//			transformUtil.world2Camera(d, d);
//			if (z == 0) {
//				gl.glColor3f(1, 0, 0);
//			} else if (z == 1) {
//				gl.glColor3f(0, 1, 0);
//			} else if (z == 2) {
//				gl.glColor3f(0, 0, 1);
//			}
//			System.out.println(z + " " + a + " " + b + " " + c + " " + d);
//			gl.glBegin(GL_QUADS);
//			gl.glVertex3f(a.x, a.y, a.z);
//			gl.glVertex3f(b.x, b.y, b.z);
//			gl.glVertex3f(c.x, c.y, c.z);
//			gl.glVertex3f(d.x, d.y, d.z);
//			gl.glEnd();
//		}
		
		gl.glEnable(GL_LIGHTING);
	}
	
	private void drawSelection(Selection selection) {	
		selection.getSelectedSdsModelAttribute().getValue().getLocal2WorldTransform(transformUtil, LOCAL);
		transformUtil.getMatrix(TransformUtil.LOCAL, TransformUtil.CAMERA, modelView);
		gl.glMatrixMode(GL_MODELVIEW);
		gl.glLoadIdentity();
		gl.glLoadMatrixd(modelView, 0);
		
		gl.glPointSize(4);
		gl.glDisable(GL_LIGHTING);
		Point3f p = new Point3f();
		for (int pass = 0; pass < 2; pass++) {
			if (pass == 0) {
				gl.glDisable(GL_DEPTH_TEST);
				gl.glEnable(GL_BLEND);
				gl.glColor4f(1, 1, 0, 0.4f);
			} else {
				gl.glEnable(GL_DEPTH_TEST);
				gl.glDisable(GL_BLEND);
				gl.glColor3f(1, 1, 0);
			}
			gl.glBegin(GL_POINTS);
			if (viewDef.getShowControlMeshAttribute().getBoolean()) {
				for (AbstractVertex vertex : selection.getSelectedVerticesAttribute().getElements()) {
					vertex.getPosition(p);
					gl.glVertex3f(p.x, p.y, p.z);
				}
			} else if (viewDef.getShowProjectedMeshAttribute().getBoolean()) {
				for (AbstractVertex vertex : selection.getSelectedVerticesAttribute().getElements()) {
					vertex.getVertexPoint().getLimit(p);
					gl.glVertex3f(p.x, p.y, p.z);
				}
			}
			gl.glEnd();
		}
		
		Point3f p0 = new Point3f();
		Point3f p1 = new Point3f();
		if (!getViewDef().getShowControlMeshAttribute().getBoolean() && selection.getVertexCount() > 1) {
			for (int pass = 0; pass < 4; pass++) {
				if (pass < 2) {
					gl.glColor4f(1, 1, 0, 0.15f);
					gl.glDisable(GL_DEPTH_TEST);
				} else {
					gl.glColor4f(1, 1, 0, 0.5f);
					gl.glEnable(GL_DEPTH_TEST);
				}
				if (pass == 0 || pass == 2) {
					gl.glBegin(GL_LINES);
				} else {
					gl.glBegin(GL_POINTS);
				}
				for (AbstractVertex v : selection.getSelectedVerticesAttribute().getElements()) {
					v.getPosition(p0);
					gl.glVertex3f(p0.x, p0.y, p0.z);
					if (pass == 0 || pass == 2) {
						v.getVertexPoint().getLimit(p1);
						gl.glVertex3f(p1.x, p1.y, p1.z);
					}
				}
				gl.glEnd();
			}
		}
		
		gl.glPointSize(3);
	}
	
	private void drawSds2(com.jpatch.entity.sds2.Sds sds, int level) {
//		transformUtil.setSpace2World(TransformUtil.LOCAL, IDENTITY);
		GlMaterial currentMaterial = null;
		
		gl.glColor3f(0, 0, 0);
		gl.glEnable(GL_COLOR_MATERIAL);
		gl.glColorMaterial(GL_FRONT, GL_EMISSION);
		gl.glInterleavedArrays(GL_N3F_V3F, 0, buffer);
		if (viewDef.getShowLimitSurfaceAttribute().getBoolean()) {
			final boolean showProjectedMesh = viewDef.getShowProjectedMeshAttribute().getBoolean();
			int n = 0;
			for (com.jpatch.entity.sds2.Face face : sds.getFaces(level - 1)) {
//				System.out.println("drawing face " + n++ + ": " + face);
				GlMaterial faceMaterial = face.getMaterial().getGlMaterial();
				if (currentMaterial != faceMaterial) {
					setMaterial(GL_FRONT, faceMaterial.getArray());
					currentMaterial = faceMaterial;
				}
				face.fillArrayLimit(buffer);
				gl.glDrawArrays(GL_TRIANGLE_FAN, 0, face.getSides() * 2 + 2);
				if (showProjectedMesh) {
					gl.glColor3f(0.5f, 0.5f, 0.5f);
					gl.glDrawArrays(GL_LINE_LOOP, 1, face.getSides() * 2);
					gl.glColor3f(0, 0, 0);
				}
			}
//			System.out.println();
		}
		
		if (viewDef.getShowControlMeshAttribute().getBoolean()) {
			gl.glDisable(GL_COLOR_MATERIAL);
			gl.glDisable(GL_LIGHTING);
			for (com.jpatch.entity.sds2.Face face : sds.getFaces(Globals.getInstance().getEditLevelAttribute().getInt())) {
				face.fillArrayPosition(buffer);
				gl.glColor3f(1, 1, 1);
				gl.glDrawArrays(GL_LINE_LOOP, 1, face.getSides());
				gl.glColor3f(1, 0, 0);
				gl.glDrawArrays(GL_POINTS, 1, face.getSides());
			}
		}
//		for (com.jpatch.entity.sds2.Face face : sds.getFaces(level)) {
//			gl.glBegin(GL_POLYGON);
//			for (com.jpatch.entity.sds2.HalfEdge edge : face.getEdges()) {
//				edge.getVertex().getPosition(p);
//				modelView.transform(p);
//				gl.glVertex3f(p.x, p.y, p.z);
//			}
//			gl.glEnd();
//		}
			
//		gl.glDisable(GL_DEPTH_TEST);
//		gl.glDisable(GL_LIGHTING);
//		gl.glColor3f(1, 1, 1);
//		gl.glBegin(GL_LINES);
//		for (com.jpatch.entity.sds2.Face face : sds.getFaces(level - 1)) {
//			for (com.jpatch.entity.sds2.HalfEdge edge : face.getEdges()) {
//				edge.getFace().getFacePoint().getLimit(p);
//				edge.getFace().getFacePoint().getNormal(n);
//				n.normalize();
//				n.scale(0.1f);
//				n.add(p);
//				gl.glVertex3f(p.x, p.y, p.z);
//				gl.glVertex3f(n.x, n.y, n.z);
//			}
//		}
//		gl.glEnd();
//		gl.glEnable(GL_LIGHTING);
//		gl.glEnable(GL_DEPTH_TEST);
//		gl.glLoadIdentity();
		
	}
	
	private void drawSds3(Sds sds) {
		useProgram = false;
		gl.glEnable(GL_LIGHTING);
		gl.glShadeModel(GL_SMOOTH);
		gl.glPolygonMode(GL_FRONT, GL_FILL);
		gl.glEnable(GL_COLOR_MATERIAL);
		gl.glColorMaterial(GL_FRONT, GL_EMISSION);
		
//		if (gl.isFunctionAvailable("glUseProgram")) {
//			gl.glUseProgram(useProgram ? program : 0);
//		}
		gl.glPointSize(3);
//		time = 0;
//		gl.glEnd();
//		for (Face face : sds.faceList) {
//			drawFace(face, subdivLevel);
//			break;
//		}
		
//		sds.computeLevel2Vertices();
		
//		Matrix4d m = new Matrix4d();
		
		sds.computeLevel2Vertices();
		sds.project(modelView);
		
		for (Face face : sds.faceList) {
			for (Slate2 slate : face.getSlates()) {
				slate.estimateSubdivLevel(component.getWidth() >> 1, component.getHeight() >> 1);
			}
		}
//		System.out.println();
//		Point3f p0 = new Point3f();
//		Point3f p1 = new Point3f();
//		gl.glInterleavedArrays(GL_N3F_V3F, 0, dicer.getBuffer());
//		gl.glEnable(GL_LIGHTING);
//		gl.glMaterialfv(GL_FRONT, GL_DIFFUSE, new float[] { 0, 0, 0.9f }, 0);
//		gl.glMaterialfv(GL_FRONT, GL_AMBIENT, new float[] { 0, 0, 0.2f }, 0);
		
//		if (canUseProgram) {
//			gl.glUseProgram(useProgram ? program : 0);
//		}
		
		GlMaterial currentMaterial = null;
		gl.glColor3f(0.0f, 0.0f, 0.0f);
		
		Point3f p = new Point3f();
		Vector3f n = new Vector3f();
		if (showLimitSurfaceAttr.getBoolean()) {
			
//			System.out.println("simple model = " + simpleModel);
			for (Face face : sds.faceList) {
				GlMaterial faceMaterial = face.getMaterial().getGlMaterial();
				if (currentMaterial != faceMaterial) {
					setMaterial(GL_FRONT, faceMaterial.getArray());
					currentMaterial = faceMaterial;
				}
				boolean simple = true;
				for (Slate2 slate : face.getSlates()) {
					if (!slate.isSimple()) {
						simple = false;
					}
				}
				if (simple) {
					gl.glBegin(GL_TRIANGLE_FAN);
					face.getFacePoint().getProjectedLimit(p);
					face.getFacePoint().getProjectedNormal(n);
					gl.glNormal3f(n.x, n.y, n.z);
					gl.glVertex3f(p.x, p.y, p.z);
					for (HalfEdge edge : face.getEdges()) {
						edge.getVertex().getVertexPoint().getProjectedLimit(p);
						edge.getVertex().getVertexPoint().getProjectedNormal(n);
						gl.glNormal3f(n.x, n.y, n.z);
						gl.glVertex3f(p.x, p.y, p.z);
						edge.getEdgePoint().getProjectedLimit(p);
						edge.getEdgePoint().getProjectedNormal(n);
						gl.glNormal3f(n.x, n.y, n.z);
						gl.glVertex3f(p.x, p.y, p.z);
					}
					face.getEdges()[0].getVertex().getVertexPoint().getProjectedLimit(p);
					face.getEdges()[0].getVertex().getVertexPoint().getProjectedNormal(n);
					gl.glNormal3f(n.x, n.y, n.z);
					gl.glVertex3f(p.x, p.y, p.z);
					gl.glEnd();
					if (showProjectedMeshAttr.getBoolean()) {
						gl.glColor3f(1, 1, 1);
						gl.glBegin(GL_LINE_LOOP);
						for (HalfEdge edge : face.getEdges()) {
							edge.getVertex().getVertexPoint().getProjectedLimit(p);
							gl.glVertex3f(p.x, p.y, p.z);
							edge.getEdgePoint().getProjectedLimit(p);
							gl.glVertex3f(p.x, p.y, p.z);
						}
						gl.glEnd();
						
						gl.glColor3f(0, 0, 0);
					}
					
				} else {
					for (Slate2 slate : face.getSlates()) {
						drawSlate(slate);
					}
				}
			}
		}
		
//		gl.glColor3f(0.0f, 0.0f, 0.0f);
//		gl.glDisable(GL_COLOR_MATERIAL);
		
		if (showControlMeshAttr.getBoolean()) {
			
			if (!showLimitSurfaceAttr.getBoolean()) {
				gl.glEnable(GL_LIGHTING);
				for (Face face : sds.faceList) {
					GlMaterial faceMaterial = face.getMaterial().getGlMaterial();
					if (currentMaterial != faceMaterial) {
						setMaterial(GL_FRONT, faceMaterial.getArray());
						currentMaterial = faceMaterial;
					}
					gl.glBegin(GL_TRIANGLE_FAN);
					face.getFacePoint().getProjectedPos(p);
					face.getFacePoint().getProjectedNormal(n);
					gl.glNormal3f(n.x, n.y, n.z);
					gl.glVertex3f(p.x, p.y, p.z);
					for (HalfEdge edge : face.getEdges()) {
						edge.getVertex().getProjectedPos(p);
//						n = edge.getFirstVertex().vertexPoint.projectedNormal;
//						gl.glNormal3f(n.x, n.y, n.z);
						gl.glVertex3f(p.x, p.y, p.z);
					}
					face.getEdges()[0].getVertex().getProjectedPos(p);
//					n = face.edge.getFirstVertex().vertexPoint.projectedNormal;
//					gl.glNormal3f(n.x, n.y, n.z);
					gl.glVertex3f(p.x, p.y, p.z);
					gl.glEnd();
				}
			}
			
			gl.glDisable(GL_LIGHTING);
//			if (canUseProgram && useProgram) {
//				gl.glUseProgram(0);
//			}
	//		if (gl.isFunctionAvailable("glUseProgram")) {
	//			gl.glUseProgram(0);
	//		}
			
			
	//		gl.glColor3f(1, 1, 1);
			gl.glBegin(GL_LINES);
			for (Face face : sds.faceList) {
				for (HalfEdge edge : face.getEdges()) {
					if (edge.isPrimary()) {
						if (edge.creaseSharpness() > 0) {
							gl.glColor3f(1, 0, 0);
						} else {
							gl.glColor3f(1, 1, 1);
						}
						edge.getVertex().getProjectedPos(p);
						gl.glVertex3f(p.x, p.y, p.z);
						edge.getPairVertex().getProjectedPos(p);
						gl.glVertex3f(p.x, p.y, p.z);
					}
				}
			}
			gl.glEnd();
		
		
		
		
			gl.glColor3f(1, 0, 0);
			gl.glBegin(GL_POINTS);
			for (Face face : sds.faceList) {
				for (HalfEdge edge : face.getEdges()) {
					if (edge.isPrimary()) {
						AbstractVertex vertex = edge.getVertex();
						vertex.getProjectedPos(p);
						gl.glVertex3f(p.x, p.y, p.z);
//						vertex = edge.getSecondVertex();
//						p = vertex.projectedPos;
//						if (selectedVertices.contains(vertex)) {
//							gl.glColor3f(0, 1, 0);
//						} else {
//							gl.glColor3f(1, 0, 0);
//						}
//						gl.glVertex3f(p.x, p.y, p.z);
						
					}
				}
//				gl.glColor3f(1, 1, 0);
//				Point3f p = face.facePoint.projectedPos;
//				gl.glVertex3f(p.x, p.y, p.z);
				
			}
			gl.glEnd();
			
//			Vector3f n = new Vector3f();
//			gl.glColor3f(1, 1, 0);
//			gl.glBegin(GL_LINES);
//			for (Face face : sds.faceList) {
//				for (HalfEdge edge : face.getEdges()) {
//					if (edge.isPrimary()) {
//						TopLevelVertex vertex = edge.getFirstVertex();
//						Point3f p = vertex.vertexPoint.projectedLimit;
//						gl.glVertex3f(p.x, p.y, p.z);
//						n.set(vertex.vertexPoint.projectedNormal);
//						n.normalize();
//						n.scale(20);
//						p.add(n);
//						gl.glVertex3f(p.x, p.y, p.z);
//					}
//				}
//			}
//			gl.glEnd();
			
			
		} else if (showProjectedMeshAttr.getBoolean()) {
			gl.glDisable(GL_LIGHTING);
			gl.glColor3f(1, 0, 0);
			gl.glBegin(GL_POINTS);
			for (Face face : sds.faceList) {
				for (HalfEdge edge : face.getEdges()) {
					if (edge.isPrimary()) {
						TopLevelVertex vertex = edge.getVertex();
						vertex.getVertexPoint().getProjectedLimit(p);
						gl.glVertex3f(p.x, p.y, p.z);
					}
				}
			}
			gl.glEnd();
		}
//		for (Level2Vertex v : sds.level2Vertices) {
//			v.getProjectedPos(p0);
//			gl.glVertex3f(p0.x, p0.y, p0.z);
//		}
		
			
		
//		gl.glBegin(GL_POINTS);
//		for (Face face : sds.faceList) {
//			for (HalfEdge edge : face.getEdges()) {
//				edge.getFirstVertex().position.get(p0);
//				modelView.transform(p0);
//				gl.glVertex3f(p0.x, p0.y, p0.z);
//			}
//		}
//		gl.glEnd();
		
//		gl.glDisable(GL_DEPTH_TEST);
//		gl.glEnable(GL_BLEND);
//		gl.glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA);
		
//		gl.glColor4f(1, 1, 1, 0.15f);
//		gl.glBegin(GL_LINES);
//		for (Face face : sds.faceList) {
//			for (HalfEdge edge : face.getEdges()) {
//				if (edge.isMaster()) {
//					edge.getFirstVertex().referencePosition.get(p0);
//					edge.getSecondVertex().referencePosition.get(p1);
//					modelView.transform(p0);
//					modelView.transform(p1);
//					gl.glVertex3f(p0.x, p0.y, p0.z);
//					gl.glVertex3f(p1.x, p1.y, p1.z);
//				}
//			}
//		}
//		gl.glEnd();
		
//		gl.glColor4f(1, 1, 1, 0.05f);
//		gl.glBegin(GL_LINES);
//		for (Face face : sds.faceList) {
//			int i = 0;
//			Slate[] slates = face.getSlates();
//			for (HalfEdge edge : face.getEdges()) {
//				edge.getFirstVertex().referencePosition.get(p0);
//				modelView.transform(p0);
////				p1.set(slates[i++].limitPoints[2]);
//				edge.getFirstVertex().limitPoint.position.get(p1);
//				modelView.transform(p1);
//				gl.glVertex3f(p0.x, p0.y, p0.z);
//				gl.glVertex3f(p1.x, p1.y, p1.z);
//			}
//		}
//		gl.glEnd();
		
//		gl.glColor4f(1, 0, 0, 0.15f);
//		gl.glBegin(GL_POINTS);
//		for (Face face : sds.faceList) {
//			for (HalfEdge edge : face.getEdges()) {
//				edge.getFirstVertex().limitPoint.position.get(p0);
//				modelView.transform(p0);
//				gl.glVertex3f(p0.x, p0.y, p0.z);
//			}
//		}
//		gl.glEnd();
//		gl.glDisable(GL_BLEND);
		
		
//		drawFace(sds.faceList.get(Math.abs(num) % sds.faceList.size()), subdivLevel);
//		System.out.println(time);
//		drawFace(null, subdivLevel);
//		System.out.println(i + " fragments@level " + subdivLevel + " in " + total + "ms");
	}
	
	private void drawSlate(Slate2 slate) {
		if (false) return;
		/*
		 * turning lighting on/off (using glEnable(GL_LIGHTING) and glDisable(GL_LIGHTING)
		 * a lot during rendering proved to be very slow. This code therefore uses
		 * GL_COLOR_MATERIAL to render the wireframe of the projected mesgh.
		 */
		final int level = slate.getSubdivLevel();
		if (level < 0) {
			return;
		}
		
		dicer.dice(slate, level);
		
//		if (l < 2) {
//			l = 2;
//		}
//		System.out.println("Slate=" + slate + " level=" + level);
		
		
//		count = (dim - 1) * (dim - 1);
//		
		
//		gl.glEnable(GL_LIGHTING);
//		if (gl.isFunctionAvailable("glUseProgram")) {
//			gl.glUseProgram(useProgram ? program : 0);
//		}

		
		
		
//		FloatBuffer buffer = dicer.getBuffer();
//		count = buffer.capacity() / 4;
//		gl.glInterleavedArrays(GL_N3F_V3F, 0, buffer);
//		gl.glDrawArrays(GL_QUADS, 0, count);
//		gl.glFlush();
//		gl.glFinish();
		
		final int start, end;
		final int dim = (1 << (level - 1)) + 3;
		if (level < 2) {
			start = 1;
			end = dim - 2;
		} else {
			start = 2;
			end = dim - 3;
		}
		int ydim = start * dim;
		final float[][] normals = dicer.getLimitNormals(level - 1);
		final float[][] vertices = dicer.getLimitVertices(level - 1);
		
		gl.glColor3f(0, 0, 0);
		gl.glBegin(GL_QUADS);
		for (int y = start; y < end; y++) {
			int gsydim = Dicer.GRID_START + ydim;
			int gsydim1 = gsydim + dim;
			for (int x = start; x < end; x++) {
				gl.glNormal3fv(normals[gsydim + x], 0);
				gl.glVertex3fv(vertices[gsydim + x], 0);
				gl.glNormal3fv(normals[gsydim + x + 1], 3);
				gl.glVertex3fv(vertices[gsydim + x + 1], 0);
				gl.glNormal3fv(normals[gsydim1 + x + 1], 6);
				gl.glVertex3fv(vertices[gsydim1 + x + 1], 0);
				gl.glNormal3fv(normals[gsydim1 + x], 9);
				gl.glVertex3fv(vertices[gsydim1 + x], 0);
			}
			ydim += dim;
		}
		gl.glEnd();

		
//		final float[] quadVertices = dicer.getQuadVertexArray(level);
//		final float[] quadNormals = dicer.getQuadNormalArray(level);
//		gl.glBegin(GL_QUADS);
//		for (int i = 0; i < count; i += 3) {
//			gl.glNormal3fv(quadNormals, i);
//			gl.glVertex3fv(quadVertices, i);
//		}
//		gl.glEnd();

		gl.glBegin(GL_TRIANGLES);
		for (int side = 0; side < 4; side++) {
			final Slate2 adjacentSlate = slate.getAdjacentSlate(side);
			int pairLevel = adjacentSlate == null ? level : adjacentSlate.getSubdivLevel();
			if (pairLevel < 0) {
				pairLevel = level;
			}
			final int[] triangleArray = dicer.getRimTriangles(level - 1, side, pairLevel - 1);
			final int[] triangleArrayNormals = dicer.getRimTriangleNormals(level - 1, side, pairLevel - 1);
			for (int i = 0; i < triangleArray.length; i++) {
				gl.glNormal3fv(normals[triangleArray[i]], triangleArrayNormals[i]);
				gl.glVertex3fv(vertices[triangleArray[i]], 0);
			}
		}
		gl.glEnd();
		
		
		
//		gl.glDisable(GL_LIGHTING);
//		if (gl.isFunctionAvailable("glUseProgram")) {
//			gl.glUseProgram(0);
//		}
		
		
		
		
//		if (gl.isFunctionAvailable("glUseProgram")) {
//			gl.glUseProgram(useProgram ? program : 0);
//		}
		
		if (showProjectedMeshAttr.getBoolean()) {
//			gl.glEnable(GL_COLOR_MATERIAL);
//			gl.glDisable(GL_LIGHTING);
//			gl.glColor3f(0.5f, 0.5f, 0.5f);
			gl.glColor3f(1.0f, 1.0f, 1.0f);
			for (int i = 0; i < 2; i++) {
				int side = (i + 3) % 4;
				if (true || slate.getCorners()[side][0].isToBeDrawn()) {
					final Slate2 adjacentSlate = slate.getAdjacentSlate(side);
					int pairLevel = adjacentSlate == null ? level : adjacentSlate.getSubdivLevel();
					if (pairLevel > level || pairLevel < 1) {
						pairLevel = level;
					}
	//				if (pairLevel < 0)
	//				if (pairLevel < 2) {
	//					pairLevel = 2;
	//				}
	//				pairLevel = level;
					final int[] lineArray = dicer.getRim(pairLevel - 1, side);
					final float[][] lineVertices = dicer.getLimitVertices(pairLevel - 1);
//					final float[][] lineNormals = dicer.getLimitNormals(pairLevel - 1);
					gl.glBegin(GL_LINE_STRIP);
					for (int j = 0; j < lineArray.length; j++) {
//						if (lineNormals[lineArray[j] + Dicer.GRID_START][2] > 0) {
//							int offset = (j > 0 && j < lineArray.length - 1) ? side * 3 : 0;
//							gl.glNormal3fv(lineNormals[lineArray[j] + Dicer.GRID_START], offset);
							gl.glVertex3fv(lineVertices[lineArray[j] + Dicer.GRID_START], 0);
//						}
					}
					gl.glEnd();
				}
			}
//			gl.glDisable(GL_COLOR_MATERIAL);
			gl.glColor3f(0.0f, 0.0f, 0.0f);
//			gl.glEnable(GL_LIGHTING);
		}
		
//		gl.glDisable(GL_LIGHTING);
//		gl.glColor3f(0.5f, 0.5f, 0.5f);
//		vertices = dicer.getSubdivVertices(subdivLevel - 1);
//		dim = ((1 << subdivLevel - 1)) + 3;
//		int start = dicer.getGridStart();
//		for (int i = 1, n = dim - 1; i < n; i++) {
//			gl.glBegin(GL_LINE_STRIP);
//			int index = start + i * dim;
//			for (int j = index + 1, m = index + dim - 1; j < m; j++) {
//				gl.glVertex3fv(vertices[j], 0);
//			}
//			gl.glEnd();
//		}
//		for (int i = 1, n = dim - 1; i < n; i++) {
//			gl.glBegin(GL_LINE_STRIP);
//			int index = start + i;
//			int max = dim * (dim - 1);
//			for (int j = index + dim, m = index + max; j < m; j += dim) {
//				gl.glVertex3fv(vertices[j], 0);
//			}
//			gl.glEnd();
//		}
		
//		final int EDGE = 1;
//		final int EDGE_H = 2;
//		final int EDGE_V = 3;
//		final int FACE = 4;
//		final int POINT = 5;
//		final int CREASE_4_5 = 6;
//		final int CREASE_4_6 = 7;
//		final int CREASE_4_7 = 8;
//		final int CREASE_5_6 = 9;
//		final int CREASE_5_7 = 10;
//		final int CREASE_6_7 = 11;
//		int[][] stencils = dicer.getStencils(subdivLevel - 1);
//		gl.glPointSize(5);
//		gl.glBegin(GL_POINTS);
//		for (int i = 1, n = dim - 1; i < n; i++) {
//			int index = start + i * dim;
//			for (int j = index + 1, m = index + dim - 1; j < m; j++) {
////				switch (stencils[j - start][0]) {
////				case EDGE:
////				case EDGE_H:
////				case EDGE_V:
////					gl.glColor3f(1, 0, 0);
////					break;
////				case FACE:
////					gl.glColor3f(0, 1, 0);
////					break;
////				case POINT:
////					gl.glColor3f(0, 1, 1);
////					break;
////				default:
////					gl.glColor3f(1, 1, 1);
////				}
//				if (stencils[j - start][0] != FACE && stencils[j - start][1] > 0) {
//					gl.glColor3f(1, 0, 0);
//				} else {
//					gl.glColor3f(0, 1, 0);
//				}
//				gl.glVertex3fv(vertices[j], 0);
//			}
//		}
//		gl.glEnd();
	}

	protected void drawInfo() {
		rasterMode();
//		gl.glColor3f(COLORS.text.x, COLORS.text.y, COLORS.text.z);
		String fps = Long.toString(1000000000 / (System.nanoTime() - time));
		drawString(getInfo(), 4, 16);
		
		drawString("repaint " + (repaintCount++) + " " + fps + "fps", 4, 32);
	}
	
	private void drawString(String string, int x, int y) {
		gl.glEnable(GL_BLEND);
		gl.glColor4f(0, 0, 0, 0.5f);
		for (int yy = y - 1; yy < y + 2; yy++) {
			for (int xx = x - 1; xx < x + 2; xx++) {
				gl.glRasterPos2i(xx, yy);							// set raster position
				char[] c = string.toCharArray();
			    for (int i = 0, n = c.length; i < n; i++) {		// loop over characters
			    	if (c[i] < 256) {
			    		gl.glCallList(fontOffset + c[i]);		// call display list that draws a character
			    	}
			    }
			}
		}
		gl.glColor4f(1, 1, 1, 0.75f);
		gl.glRasterPos2i(x, y);							// set raster position
		char[] c = string.toCharArray();
	    for (int i = 0, n = c.length; i < n; i++) {		// loop over characters
	    	if (c[i] < 256) {
	    		gl.glCallList(fontOffset + c[i]);		// call display list that draws a character
	    	}
	    }
	    gl.glDisable(GL_BLEND);
	}
	
	private void spatialMode() {
		float w = (float) component.getWidth() / 2;
		float h = (float) component.getHeight() / 2;
		gl.glMatrixMode(GL_PROJECTION);
		gl.glLoadIdentity();
		if (viewDef instanceof PerspectiveViewDef) {
			PerspectiveViewDef perspectiveView = ((PerspectiveViewDef) viewDef);
//			float a = (float) (17.5 / perspective.getFocalLength());
			float a = 0.5f / (float) perspectiveView.getRelativeFocalLength();
			float b = a * h / w;
//			float a = 17.5f / (float) camera.focalLength.get(); 	// 35/focallength/2
//			float b = a * h / w;
			gl.glFrustum(-a, a, -b, b, nearClip, farClip);
		} else {
			gl.glOrtho(-w, w, -h, h, -farClip, farClip);
		}
		gl.glDepthFunc(GL_LEQUAL);
		gl.glMatrixMode(GL_MODELVIEW);
		gl.glLoadIdentity();
//		gl.glScalef(1, 1, -1); // switch to left handed coordinate system
		gl.glEnable(GL_DEPTH_TEST);
	}
	
	public void rasterMode() {
		int w = drawable.getWidth();
		int h = drawable.getHeight();
		gl.glViewport(0, 0, w - 1, h - 1);
	    gl.glMatrixMode(GL_PROJECTION);
	    gl.glLoadIdentity();
	    gl.glOrtho(0, w - 1, h - 1, 0, 1, -1);
	    gl.glMatrixMode(GL_MODELVIEW);
	    gl.glLoadIdentity();
	    gl.glDisable(GL_LIGHTING);
		gl.glDisable(GL_DEPTH_TEST);
		gl.glShadeModel(GL_FLAT);
	}
	
	private void loadShader(InputStream in, GL gl, int shader) throws IOException {
		BufferedReader reader = new BufferedReader(new InputStreamReader(in));
		String line;
		List<String> list = new ArrayList<String>(128);
		while ((line = reader.readLine()) != null) {
			list.add(line + "\n");
		}
		String[] source = list.toArray(new String[list.size()]);
		int[] length = new int[source.length];
		for (int i = 0; i < length.length; i++) {
			length[i] = source[i].length();
		}
		gl.glShaderSource(shader, source.length, source, length, 0);
		in.close();
	}
	
	private void printShaderInfo(GL gl, int shader) {
		int[] info = new int[5];
		gl.glGetShaderiv(shader, GL_SHADER_TYPE, info, 0);
		gl.glGetShaderiv(shader, GL_DELETE_STATUS, info, 1);
		gl.glGetShaderiv(shader, GL_COMPILE_STATUS, info, 2);
		gl.glGetShaderiv(shader, GL_INFO_LOG_LENGTH, info, 3);
		gl.glGetShaderiv(shader, GL_SHADER_SOURCE_LENGTH, info, 4);
		System.out.println("Shader Info for shader " + shader);
		System.out.println("=========================");
		System.out.println("GL_SHADER_TYPE = " + (info[0] == GL_VERTEX_SHADER ? "GL_VERTEX_SHADER" : info[0] == GL_FRAGMENT_SHADER ? "GL_FRAGMENT_SHADER" : "unknown"));
		System.out.println("GL_DELETE_STATUS = " + (info[1] == GL_TRUE ? "true" : "false"));
		System.out.println("GL_COMPILE_STATUS = " + (info[2] == GL_TRUE ? "true" : "false"));
		System.out.println("GL_INFO_LOG_LENGTH = " + info[3]);
		System.out.println("GL_SHADER_SOURCE_LENGTH = " + info[4]);
		System.out.println();
		int infoLogLength = info[3];
		if (infoLogLength > 0) {
			int[] length = new int[1];
			byte[] infoLog = new byte[infoLogLength];
			gl.glGetShaderInfoLog(shader, infoLogLength, length, 0, infoLog, 0);
			System.out.println(new String(infoLog));
		}
	}
	
	private void printProgramInfo(GL gl, int program) {
		int[] info = new int[9];
		gl.glGetProgramiv(program, GL_DELETE_STATUS, info, 0);
		gl.glGetProgramiv(program, GL_LINK_STATUS, info, 1);
		gl.glGetProgramiv(program, GL_VALIDATE_STATUS, info, 2);
		gl.glGetProgramiv(program, GL_INFO_LOG_LENGTH, info, 3);
		gl.glGetProgramiv(program, GL_ATTACHED_SHADERS, info, 4);
		gl.glGetProgramiv(program, GL_ACTIVE_ATTRIBUTES, info, 5);
		gl.glGetProgramiv(program, GL_ACTIVE_ATTRIBUTE_MAX_LENGTH, info, 6);
		gl.glGetProgramiv(program, GL_ACTIVE_UNIFORMS, info, 7);
		gl.glGetProgramiv(program, GL_ACTIVE_UNIFORM_MAX_LENGTH, info, 8);	
		
		System.out.println("Program Info for program " + program);
		System.out.println("=========================");
		System.out.println("GL_DELETE_STATUS = " + (info[0] == GL_TRUE ? "true" : "false"));
		System.out.println("GL_LINK_STATUS = " + (info[1] == GL_TRUE ? "true" : "false"));
		System.out.println("GL_VALIDATE_STATUS = " + (info[2] == GL_TRUE ? "true" : "false"));
		System.out.println("GL_INFO_LOG_LENGTH = " + info[3]);
		System.out.println("GL_ATTACHED_SHADERS = " + info[4]);
		System.out.println("GL_ACTIVE_ATTRIBUTES = " + info[5]);
		System.out.println("GL_ACTIVE_ATTRIBUTE_MAX_LENGTH = " + info[6]);
		System.out.println("GL_ACTIVE_UNIFORMS = " + info[7]);
		System.out.println("GL_ACTIVE_UNIFORM_MAX_LENGTH = " + info[8]);
		System.out.println();
		int infoLogLength = info[3];
		if (infoLogLength > 0) {
			int[] length = new int[1];
			byte[] infoLog = new byte[infoLogLength];
			gl.glGetProgramInfoLog(program, infoLogLength, length, 0, infoLog, 0);
			System.out.println(new String(infoLog));
		}
	}
}
